# Generated by Django 6.0.7 on 2026-07-14 10:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        help_text="Montant en FCFA, capturé au moment du paiement (indépendant d'un changement de prix ultérieur du Plan)."
                    ),
                ),
                ("phone_number", models.CharField(max_length=9)),
                (
                    "external_reference",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("campay_reference", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("SUCCESSFUL", "Réussie"),
                            ("FAILED", "Échouée"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
