# Generated by Django 6.0.7 on 2026-07-15 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_lesson_pdf_price"),
        ("payments", "0002_initial"),
        ("subscriptions", "0002_seed_plans"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                help_text="Renseigné uniquement pour un achat de type PDF (déblocage à l'unité).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="unlock_transactions",
                to="catalog.lesson",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("ABONNEMENT", "Abonnement"),
                    ("PDF", "Déblocage PDF à l'unité"),
                ],
                default="ABONNEMENT",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.PositiveIntegerField(
                help_text="Montant en FCFA, capturé au moment du paiement (indépendant d'un changement de prix ultérieur)."
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="subscriptions.plan",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                help_text="Renseigné une fois le paiement d'abonnement confirmé et l'abonnement activé/prolongé.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="subscriptions.subscription",
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("lesson__isnull", True),
                        ("plan__isnull", False),
                        ("transaction_type", "ABONNEMENT"),
                    ),
                    models.Q(
                        ("lesson__isnull", False),
                        ("plan__isnull", True),
                        ("transaction_type", "PDF"),
                    ),
                    _connector="OR",
                ),
                name="transaction_target_matches_type",
            ),
        ),
    ]
