# Generated by Django 6.0.7 on 2026-07-16 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_transaction_lesson_transaction_transaction_type_and_more"),
        ("subscriptions", "0002_seed_plans"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="transaction",
            name="transaction_target_matches_type",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="subscriptions.plan",
            ),
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="lesson",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="transaction_type",
        ),
    ]
