# Generated by Django 6.0.7 on 2026-07-19 18:56

import random
import string

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

_ALPHABET = string.ascii_uppercase + string.digits


def _backfill_referral_codes(apps, schema_editor):
    User = apps.get_model("users", "User")
    existing = set(User.objects.exclude(referral_code="").values_list("referral_code", flat=True))
    for user in User.objects.filter(referral_code=""):
        while True:
            code = "".join(random.choices(_ALPHABET, k=6))
            if code not in existing:
                existing.add(code)
                break
        user.referral_code = code
        user.save(update_fields=["referral_code"])


def _reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_otpcode"),
    ]

    operations = [
        # unique=False ici : deux utilisateurs existants recevraient sinon le même
        # défaut "" et violeraient la contrainte avant que le backfill ci-dessous
        # ait pu s'exécuter. La contrainte unique est ajoutée dans une opération
        # séparée, une fois tous les codes réellement uniques en base.
        migrations.AddField(
            model_name="user",
            name="referral_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Code de parrainage opaque, généré à la création - jamais le numéro de téléphone.",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Renseigné une seule fois, à l'inscription, si un code de parrainage valide a été fourni.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="filleuls",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(_backfill_referral_codes, _reverse_noop),
        migrations.AlterField(
            model_name="user",
            name="referral_code",
            field=models.CharField(
                blank=True,
                help_text="Code de parrainage opaque, généré à la création - jamais le numéro de téléphone.",
                max_length=10,
                unique=True,
            ),
        ),
    ]
