# Generated by Django 6.0.7 on 2026-07-14 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cursus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "examen",
                    models.CharField(
                        choices=[
                            ("BEPC", "BEPC"),
                            ("PROBATOIRE", "Probatoire"),
                            ("BAC", "BAC"),
                            ("AUTRE", "Devoir surveillé / Autre"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "cursus",
                "ordering": ["examen", "series"],
            },
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=1, unique=True)),
                ("label", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("label", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "lesson_type",
                    models.CharField(
                        choices=[
                            ("FICHE", "Fiche de révision"),
                            ("CORR", "Corrigé d'annale"),
                            ("SUJET", "Sujet inédit"),
                        ],
                        max_length=10,
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "epreuve_source",
                    models.CharField(
                        blank=True,
                        help_text="Nom du fichier PDF d'origine (CORR uniquement, vide pour FICHE/SUJET).",
                        max_length=255,
                    ),
                ),
                (
                    "content_markdown",
                    models.TextField(
                        blank=True,
                        help_text="Source Markdown rendue en PDF par le pipeline Playwright. Rédigée directement pour FICHE/SUJET, ou compilée depuis les Exercise validés pour CORR.",
                    ),
                ),
                (
                    "file_key",
                    models.CharField(
                        blank=True,
                        help_text="Clé R2 du PDF final, vide tant que non compilé.",
                        max_length=500,
                    ),
                ),
                (
                    "preview_key",
                    models.CharField(
                        blank=True,
                        help_text="Clé R2 de l'image de prévisualisation (page 1).",
                        max_length=500,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("VALIDE", "Validé"),
                            ("REJETE", "Rejeté"),
                        ],
                        default="BROUILLON",
                        max_length=10,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cursus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lessons",
                        to="catalog.cursus",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lessons",
                        to="catalog.subject",
                    ),
                ),
                (
                    "mots_cles_recherche",
                    models.ManyToManyField(
                        blank=True, related_name="lessons_as_keyword", to="catalog.tag"
                    ),
                ),
                (
                    "themes",
                    models.ManyToManyField(
                        blank=True, related_name="lessons_as_theme", to="catalog.tag"
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "title"],
            },
        ),
        migrations.AddField(
            model_name="cursus",
            name="series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cursus_set",
                to="catalog.series",
            ),
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_exercice", models.CharField(max_length=10)),
                ("points", models.CharField(blank=True, max_length=20)),
                ("enonce_markdown", models.TextField()),
                ("corrige_markdown", models.TextField()),
                (
                    "difficulte_estimee",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FAIBLE", "Faible"),
                            ("MOYENNE", "Moyenne"),
                            ("ELEVEE", "Élevée"),
                        ],
                        max_length=10,
                    ),
                ),
                ("incertitudes", models.JSONField(blank=True, default=list)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("VALIDE", "Validé"),
                            ("REJETE", "Rejeté"),
                        ],
                        default="BROUILLON",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        help_text="Épreuve/groupe auquel appartient cet exercice, renseigné dès l'ingestion.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exercises",
                        to="catalog.lesson",
                    ),
                ),
                (
                    "mots_cles_recherche",
                    models.ManyToManyField(
                        blank=True,
                        related_name="exercises_as_keyword",
                        to="catalog.tag",
                    ),
                ),
                (
                    "themes",
                    models.ManyToManyField(
                        blank=True, related_name="exercises_as_theme", to="catalog.tag"
                    ),
                ),
            ],
            options={
                "ordering": ["lesson", "numero_exercice"],
            },
        ),
        migrations.AddConstraint(
            model_name="cursus",
            constraint=models.UniqueConstraint(
                fields=("examen", "series"), name="unique_cursus_combo"
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["subject", "lesson_type"], name="catalog_les_subject_1efb80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exercise",
            index=models.Index(fields=["statut"], name="catalog_exe_statut_d6b05b_idx"),
        ),
    ]
