# Generated by Django 6.0.7 on 2026-07-14 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_seed_referentiel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="series",
            options={"ordering": ["code"], "verbose_name_plural": "séries"},
        ),
    ]
