# Generated by Django 6.0.7 on 2026-07-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_exercise_unique_exercice_par_lesson"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="cursus",
        ),
        migrations.AddField(
            model_name="lesson",
            name="cursus",
            field=models.ManyToManyField(
                help_text="Plusieurs cursus si l'épreuve est commune à plusieurs séries (ex: Maths BAC C/E).",
                related_name="lessons",
                to="catalog.cursus",
            ),
        ),
    ]
