# Generated by Django 6.0.7 on 2026-07-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_remove_lesson_cursus_lesson_cursus"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="pdf_price",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Prix en FCFA pour débloquer le téléchargement PDF à l'unité. Vide = téléchargement non proposé (lecture en ligne uniquement).",
                null=True,
            ),
        ),
    ]
