# Generated by Django 6.0.7 on 2026-07-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_lesson_pdf_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="coefficient",
            field=models.CharField(
                blank=True,
                help_text="Ex : 7. Affiché dans l'en-tête (lecture en ligne et PDF), jamais dans le corps du contenu.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="duree_epreuve",
            field=models.CharField(
                blank=True,
                help_text="Ex : 4h. Affiché dans l'en-tête (lecture en ligne et PDF), jamais dans le corps du contenu.",
                max_length=50,
            ),
        ),
    ]
