# Generated by Django 6.0.7 on 2026-07-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_lesson_coefficient_lesson_duree_epreuve"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="file_key",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="pdf_price",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="preview_key",
        ),
        migrations.AlterField(
            model_name="lesson",
            name="coefficient",
            field=models.CharField(
                blank=True,
                help_text="Ex : 7. Affiché dans l'en-tête, jamais dans le corps du contenu.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="content_markdown",
            field=models.TextField(
                blank=True,
                help_text="Source Markdown rendue en lecture en ligne. Rédigée directement pour FICHE/SUJET, ou compilée depuis les Exercise validés pour CORR.",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="duree_epreuve",
            field=models.CharField(
                blank=True,
                help_text="Ex : 4h. Affiché dans l'en-tête, jamais dans le corps du contenu.",
                max_length=50,
            ),
        ),
    ]
