# Generated by Django 6.0.7 on 2026-07-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_seed_litterature"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="sujet_pdf",
            field=models.FileField(
                blank=True,
                help_text="PDF brandé du sujet (énoncés uniquement, jamais le corrigé) - support marketing librement partageable. Généré hors ligne, jamais à la volée : voir la commande `generate_sujet_pdfs` ou l'action admin correspondante.",
                null=True,
                upload_to="sujets_pdf/",
            ),
        ),
    ]
