# Generated by Django 6.0.7 on 2026-07-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_alter_lesson_sujet_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="etablissement",
            field=models.CharField(
                blank=True,
                help_text="Nom de l'établissement (ORIGINE=ETABLISSEMENT uniquement).",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="origine",
            field=models.CharField(
                choices=[
                    ("OFFICIEL", "Sujet officiel"),
                    ("BLANC", "Examen blanc"),
                    ("ETABLISSEMENT", "Épreuve d'établissement"),
                    ("AUTRE", "Autre"),
                ],
                default="OFFICIEL",
                help_text="Sujet officiel, examen blanc ou épreuve d'établissement.",
                max_length=20,
            ),
        ),
    ]
