# Generated by Django 6.0.7 on 2026-07-19 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0015_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="Figure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        help_text="Identifiant du placeholder dans le Markdown (ex: fig-1) - unique seulement au sein d'un exercice.",
                        max_length=20,
                    ),
                ),
                ("image", models.FileField(upload_to="figures/")),
                (
                    "page_source",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "type_figure",
                    models.CharField(
                        blank=True,
                        help_text="Ex : figure geometrique, courbe, tableau, schema, document, carte, graphique (valeur libre, non contrainte).",
                        max_length=30,
                    ),
                ),
                ("legende", models.CharField(blank=True, max_length=500)),
                ("indispensable", models.BooleanField(default=True)),
                (
                    "lisibilite",
                    models.CharField(
                        blank=True,
                        help_text="bonne / partielle / illisible (valeur libre, non contrainte).",
                        max_length=10,
                    ),
                ),
                (
                    "origine",
                    models.CharField(
                        choices=[("ENONCE", "Énoncé"), ("CORRIGE", "Corrigé")],
                        default="ENONCE",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="figures",
                        to="catalog.exercise",
                    ),
                ),
            ],
            options={
                "ordering": ["exercise", "external_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("exercise", "external_id"),
                        name="unique_figure_par_exercice",
                    )
                ],
            },
        ),
    ]
