# Generated by Django 6.0.7 on 2026-07-19 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0016_figure"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "examen",
                    models.CharField(
                        choices=[
                            ("BEPC", "BEPC"),
                            ("PROBATOIRE", "Probatoire"),
                            ("BAC", "BAC"),
                            ("AUTRE", "Devoir surveillé / Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("annee", models.PositiveSmallIntegerField()),
                (
                    "date_debut",
                    models.DateField(
                        help_text="Premier jour de la session d'examen (calendrier officiel)."
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_sessions",
                        to="catalog.country",
                    ),
                ),
            ],
            options={
                "ordering": ["annee", "examen"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("country", "examen", "annee"),
                        name="unique_exam_session",
                    )
                ],
            },
        ),
    ]
