# Generated by Django 6.0.7 on 2026-07-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0018_seed_eps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="numero_exercice",
            field=models.CharField(
                help_text="Ex : 1, 2, 3a - mais aussi tout autre repère utilisé par l'épreuve source (ex. 'Section III' sur certaines épreuves d'anglais), pas seulement une numérotation simple.",
                max_length=30,
            ),
        ),
    ]
