# Generated by Django 6.0.7 on 2026-07-25 02:55

from django.db import migrations, models


def seed_cm_dial_code(apps, schema_editor):
    Country = apps.get_model("catalog", "Country")
    Country.objects.filter(code="CM").update(dial_code="237")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0019_alter_exercise_numero_exercice"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="dial_code",
            field=models.CharField(
                blank=True,
                help_text="Indicatif téléphonique international, sans le + (ex : 237).",
                max_length=5,
            ),
        ),
        migrations.RunPython(seed_cm_dial_code, noop),
    ]
