# Generated by Django 6.0.7 on 2026-07-25 06:02

from django.db import migrations, models


def seed_cm_currency(apps, schema_editor):
    Country = apps.get_model("catalog", "Country")
    Country.objects.filter(code="CM").update(currency="XAF")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0020_country_dial_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="currency",
            field=models.CharField(
                blank=True,
                help_text="Code devise ISO 4217 (ex : XAF). Donnée seule pour l'instant - aucun code ne s'en sert encore : le paiement (Campay) ne gère que le Cameroun.",
                max_length=3,
            ),
        ),
        migrations.RunPython(seed_cm_currency, noop),
    ]
