# Generated by Django 6.0.7 on 2026-07-25 06:18

import django.db.models.deletion
from django.db import migrations, models


def backfill_cm(apps, schema_editor):
    Country = apps.get_model("catalog", "Country")
    Subject = apps.get_model("catalog", "Subject")
    Series = apps.get_model("catalog", "Series")
    cameroun = Country.objects.get(code="CM")
    Subject.objects.filter(country__isnull=True).update(country=cameroun)
    Series.objects.filter(country__isnull=True).update(country=cameroun)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0021_country_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="series",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="series_set",
                to="catalog.country",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subjects",
                to="catalog.country",
            ),
        ),
        migrations.RunPython(backfill_cm, noop),
        migrations.AlterField(
            model_name="series",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="series_set",
                to="catalog.country",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subjects",
                to="catalog.country",
            ),
        ),
        migrations.AlterField(
            model_name="series",
            name="code",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="subject",
            name="code",
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name="series",
            constraint=models.UniqueConstraint(
                fields=("country", "code"), name="unique_series_par_pays"
            ),
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.UniqueConstraint(
                fields=("country", "code"), name="unique_subject_par_pays"
            ),
        ),
    ]
