# Generated by Django 6.0.7 on 2026-07-25 22:06

import django.db.models.deletion
from django.db import migrations, models


def seed_senegal_bfem(apps, schema_editor):
    # SN n'est pas seedé par une migration (ajouté à la main via l'admin, comme les
    # autres pays au-delà du Cameroun) - défensif, pas d'erreur si absent (ex: base de
    # test fraîche).
    Country = apps.get_model("catalog", "Country")
    ExamenLabel = apps.get_model("catalog", "ExamenLabel")
    senegal = Country.objects.filter(code="SN").first()
    if senegal:
        ExamenLabel.objects.get_or_create(country=senegal, examen="BEPC", defaults={"label": "BFEM"})


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0022_subject_series_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamenLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "examen",
                    models.CharField(
                        choices=[
                            ("BEPC", "BEPC"),
                            ("PROBATOIRE", "Probatoire"),
                            ("BAC", "BAC"),
                            ("AUTRE", "Devoir surveillé / Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Ex : BFEM (pour le Sénégal, examen=BEPC).",
                        max_length=100,
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examen_labels",
                        to="catalog.country",
                    ),
                ),
            ],
            options={
                "ordering": ["country", "examen"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("country", "examen"),
                        name="unique_examen_label_par_pays",
                    )
                ],
            },
        ),
        migrations.RunPython(seed_senegal_bfem, noop),
    ]
