# Generated by Django 6.0.7 on 2026-07-26 11:28

import django.db.models.deletion
from django.db import migrations, models


def backfill_question_per_exercise(apps, schema_editor):
    """
    enonce_markdown/corrige_markdown deviennent des champs compilés depuis Question
    (voir Exercise.compile_from_questions) - sans backfill, tout Exercise déjà en base
    perdrait son contenu au premier appel de compile_from_questions() (questions vide
    -> champs vidés). Crée une Question unique par Exercise existant, copiant son
    contenu tel quel : la vraie sous-structure (QCM, sous-parties numérotées) n'est pas
    récupérable rétroactivement sans re-traitement, seul le contenu ingéré après ce
    chantier bénéficie de la granularité par sous-question - voir le plan de ce chantier.
    """
    Exercise = apps.get_model("catalog", "Exercise")
    Question = apps.get_model("catalog", "Question")

    for exercise in Exercise.objects.filter(questions__isnull=True):
        question = Question.objects.create(
            exercise=exercise,
            numero=exercise.numero_exercice,
            ordre=1,
            enonce_markdown=exercise.enonce_markdown,
            corrige_markdown=exercise.corrige_markdown,
            difficulte_estimee=exercise.difficulte_estimee,
        )
        question.themes.set(exercise.themes.all())


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0023_examen_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="enonce_intro_markdown",
            field=models.TextField(
                blank=True,
                help_text="Préambule partagé par toutes les sous-questions (ex. consigne commune d'un QCM), affiché avant la première Question. Vide si l'exercice n'a pas de préambule propre (le cas le plus courant).",
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="corrige_markdown",
            field=models.TextField(
                blank=True,
                help_text="Compilé depuis les Question rattachées - voir compile_from_questions().",
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="enonce_markdown",
            field=models.TextField(
                blank=True,
                help_text="Compilé depuis les Question rattachées - voir compile_from_questions().",
            ),
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        help_text="Repère au sein de l'exercice parent (ex : 1, 2, a, b) - pas forcément numero_exercice.",
                        max_length=10,
                    ),
                ),
                (
                    "ordre",
                    models.PositiveSmallIntegerField(
                        help_text="Ordre d'affichage/résolution au sein de l'exercice."
                    ),
                ),
                ("enonce_markdown", models.TextField()),
                ("corrige_markdown", models.TextField()),
                (
                    "difficulte_estimee",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FAIBLE", "Faible"),
                            ("MOYENNE", "Moyenne"),
                            ("ELEVEE", "Élevée"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "type_reponse",
                    models.CharField(
                        choices=[
                            ("OUVERTE", "Réponse ouverte (auto-évaluation)"),
                            ("QCM", "Choix multiple (correction automatique)"),
                        ],
                        default="OUVERTE",
                        max_length=10,
                    ),
                ),
                (
                    "choix",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"lettre": "a", "texte": "..."}] si type_reponse=QCM, sinon vide.',
                    ),
                ),
                (
                    "reponse_correcte",
                    models.CharField(
                        blank=True,
                        help_text="Lettre correcte si type_reponse=QCM (ex : 'b'), sinon vide.",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="catalog.exercise",
                    ),
                ),
                (
                    "themes",
                    models.ManyToManyField(
                        blank=True, related_name="questions_as_theme", to="catalog.tag"
                    ),
                ),
            ],
            options={
                "ordering": ["exercise", "ordre"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("exercise", "numero"),
                        name="unique_question_par_exercice",
                    )
                ],
            },
        ),
        migrations.RunPython(backfill_question_per_exercise, noop),
    ]
