# Generated by Django 6.0.7 on 2026-07-26 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0024_question_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="difficulte_estimee",
        ),
    ]
