# Generated by Django 6.0.7 on 2026-08-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0025_remove_exercise_difficulte"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="actif",
            field=models.BooleanField(
                default=True,
                help_text="Décoche pour retirer entièrement ce pays du frontend (catalogue, cours, quiz, sitemap) sans supprimer ses données ni bloquer son ingestion - utile pour préparer un pays avant son lancement public, ou le retirer temporairement. L'ingestion (catalog.ingestion) ne consulte jamais ce champ : elle continue d'accepter du contenu pour un pays désactivé.",
            ),
        ),
    ]
