# Generated by Django 6.0.7 on 2026-08-05 11:41

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_lesson_slug_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure',
            name='image',
            field=models.FileField(upload_to=catalog.models.figure_upload_to),
        ),
    ]
