# Generated by Django 6.0.7 on 2026-08-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0030_alter_figure_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="est_vitrine",
            field=models.BooleanField(
                default=False,
                help_text="Corrigé complet en accès libre, sans abonnement ni connexion - pour qu'un visiteur juge la qualité réelle avant de payer. À réserver à une épreuve par cursus, choisie à la main : rien n'empêche techniquement d'en cocher plusieurs.",
            ),
        ),
    ]
