# Generated by Django 6.0.7 on 2026-08-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0031_lesson_est_vitrine"),
    ]

    operations = [
        migrations.CreateModel(
            name="Temoignage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("auteur_nom", models.CharField(max_length=100)),
                (
                    "auteur_description",
                    models.CharField(
                        blank=True,
                        help_text="Ex : « Terminale D, Cameroun » ou « Bachelière 2025 » - jamais de numéro de téléphone ni d'identifiant.",
                        max_length=150,
                    ),
                ),
                ("contenu", models.TextField(max_length=600)),
                (
                    "note",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Note sur 5, optionnelle - laisser vide si le témoignage n'en comporte pas.",
                        null=True,
                    ),
                ),
                ("est_publie", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
