# Generated by Django 6.0.7 on 2026-08-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_seed_physique_chimie_technologie'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='nature_epreuve',
            field=models.CharField(blank=True, choices=[('THEORIQUE', 'Théorique'), ('PRATIQUE', 'Pratique')], help_text="Théorique/Pratique quand l'épreuve source le précise (ex : Physique pratique au BAC C) - vide si cette distinction n'existe pas pour cette matière ou n'est pas déterminable, jamais deviné à l'ingestion.", max_length=10),
        ),
    ]
