# Generated by Django 6.0.7 on 2026-08-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0040_alter_figure_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='numero',
            field=models.CharField(help_text="Repère au sein de l'exercice parent (ex : 1, 2, a, b) - pas forcément numero_exercice.", max_length=20),
        ),
    ]
