# Generated by Django 6.0.7 on 2026-08-12 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0042_seed_education_civique'),
        ('programme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='savoir_officiel',
            field=models.ForeignKey(blank=True, help_text="Rattachement au référentiel programme officiel (voir programme.Savoir) - additif et rempli progressivement, rien ne dépend de ce champ pour fonctionner. Le vocabulaire Tag reste plus fin qu'un Savoir (plusieurs tags par savoir) : ce n'est pas un remplacement, juste un regroupement pédagogique par-dessus.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='programme.savoir'),
        ),
    ]
