# Generated by Django 6.0.7 on 2026-08-19 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0044_seed_espagnol"),
        ("programme", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="filiere_serie_a",
            field=models.CharField(
                blank=True,
                choices=[("ABI", "A4 Bilingue")],
                help_text='ABI (A4 Bilingue) quand l\'épreuve source précise cette filière de la Série A (vue sous la forme "A-ABI") - vide pour la Série A classique ou toute autre série. Reste rattachée à la Série A (même Cursus) - voir FiliereSerieA.',
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="institution",
            field=models.CharField(
                blank=True,
                help_text="Organisme qui ORGANISE l'examen (ex : Office du Baccalauréat du Cameroun, MINESEC), à distinguer d'`etablissement` qui dit où l'épreuve a été composée. Rempli automatiquement à l'ingestion pour un sujet officiel (voir INSTITUTIONS_OFFICIELLES) ; à saisir à la main pour un examen blanc dont l'organisateur est connu. Vide quand l'information n'est pas disponible.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="introduction_markdown",
            field=models.TextField(
                blank=True,
                help_text="Consigne(s) valables pour l'épreuve ENTIÈRE (ex : « le candidat traitera un seul sujet au choix », « l'épreuve comporte deux parties indépendantes ») - affichée une seule fois avant le premier exercice, jamais répétée. Distinct de Exercise.enonce_intro_markdown, qui ne porte qu'un préambule propre à UN exercice (CORR uniquement, complété au fil des exercices ingérés - voir catalog.ingestion).",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="partie_epreuve_francais",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ETUDE_TEXTE", "Étude de texte"),
                    ("EXPRESSION_ECRITE", "Expression écrite"),
                    ("ORTHOGRAPHE", "Orthographe"),
                ],
                help_text="Étude de texte / Expression écrite / Orthographe quand l'épreuve de Français source la précise - vide pour toute autre matière, ou pour une épreuve de Français dont la partie n'est pas déterminable. Champ dédié, distinct de nature_epreuve (voir PartieEpreuveFrancais).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="variante_sujet",
            field=models.CharField(
                blank=True,
                choices=[("SUJET_1", "Sujet 1"), ("SUJET_2", "Sujet 2")],
                help_text="Sujet 1 / Sujet 2 quand l'épreuve source précise laquelle des versions alternatives d'un même examen officiel elle transcrit - vide si une seule version existe ou si l'information n'est pas déterminable. Générique (toute matière), distinct de partie_epreuve_francais (voir VarianteSujet).",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="savoir_officiel",
            field=models.ForeignKey(
                blank=True,
                help_text="Rattachement direct au référentiel programme officiel, tel que déclaré par `savoir_officiel` dans le JSON de la sous-question. Doublonne volontairement Tag.savoir_officiel, qui reste la voie historique : ce dernier est posé sur un Tag PARTAGÉ entre questions, avec une FK unique, donc il ne peut pas représenter un tag qui vit dans deux programmes à la fois (« dérivée » en 1ère et en Tle, « limites » en BAC C et en BAC D). La précision par question était jusqu'ici perdue à l'ingestion : le JSON la portait, la base ne savait pas la stocker. Ici il n'y a aucune ambiguïté possible - une question appartient à un exercice, donc à une épreuve, donc à un cursus.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="programme.savoir",
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="groupe",
            field=models.CharField(
                choices=[("GENERAL", "Général"), ("TECHNIQUE", "Technique")],
                default="GENERAL",
                help_text="Général ou Technique - voir Groupe.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cursus",
            name="examen",
            field=models.CharField(
                choices=[
                    ("BEPC", "BEPC"),
                    ("PROBATOIRE", "Probatoire"),
                    ("BAC", "BAC"),
                    ("CAP", "CAP"),
                    ("AUTRE", "Devoir surveillé / Autre"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="examenlabel",
            name="examen",
            field=models.CharField(
                choices=[
                    ("BEPC", "BEPC"),
                    ("PROBATOIRE", "Probatoire"),
                    ("BAC", "BAC"),
                    ("CAP", "CAP"),
                    ("AUTRE", "Devoir surveillé / Autre"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="examsession",
            name="examen",
            field=models.CharField(
                choices=[
                    ("BEPC", "BEPC"),
                    ("PROBATOIRE", "Probatoire"),
                    ("BAC", "BAC"),
                    ("CAP", "CAP"),
                    ("AUTRE", "Devoir surveillé / Autre"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="origine",
            field=models.CharField(
                choices=[
                    ("OFFICIEL", "Sujet officiel"),
                    ("BLANC", "Examen blanc"),
                    ("SUJET_ZERO", "Sujet zéro"),
                    ("ETABLISSEMENT", "Épreuve d'établissement"),
                    ("AUTRE", "Autre"),
                ],
                default="OFFICIEL",
                help_text="Sujet officiel, examen blanc ou épreuve d'établissement.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="series",
            name="code",
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name="Filiere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30)),
                ("label", models.CharField(max_length=150)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="filieres",
                        to="catalog.country",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "filières",
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="series",
            name="filiere",
            field=models.ForeignKey(
                blank=True,
                help_text="Grande famille technique (STT/STI/...) - vide pour une série générale.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="series_set",
                to="catalog.filiere",
            ),
        ),
        migrations.AddConstraint(
            model_name="filiere",
            constraint=models.UniqueConstraint(
                fields=("country", "code"), name="unique_filiere_par_pays"
            ),
        ),
    ]
