# Generated by Django 6.0.7 on 2026-08-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0046_filiere_technique_cm"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="groupes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Pile ordonnée des repères de groupe (Partie/section romaine/matière) portés par cet exercice, renseignée depuis le JSON source à l'ingestion - voir catalog.rendering._exercise_group_paths pour le fallback par analyse de texte utilisé quand ce champ est vide (tout exercice ingéré avant l'introduction de ce champ, ou toute épreuve sans structure imbriquée - cas très majoritaire).",
            ),
        ),
    ]
