# Generated by Django 6.0.7 on 2026-08-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0047_exercise_groupes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure',
            name='legende',
            field=models.TextField(blank=True),
        ),
    ]
