# Generated by Django 6.0.7 on 2026-09-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0051_seed_allemand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='coefficient',
            field=models.CharField(blank=True, help_text="Ex : 7, ou une valeur composite quand elle diffère par série sur une même épreuve (ex : « 3 (série A) / 2 (séries C, D, TI) »). Affiché dans l'en-tête, jamais dans le corps du contenu.", max_length=50),
        ),
    ]
