# Generated by Django 6.0.7 on 2026-09-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0054_exercise_groupes_verifies_alter_exercise_groupes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursus',
            name='examen',
            field=models.CharField(choices=[('BEPC', 'BEPC'), ('PROBATOIRE', 'Probatoire'), ('BAC', 'BAC'), ('CAP', 'CAP'), ('GCE', 'GCE'), ('AUTRE', 'Devoir surveillé / Autre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='examenlabel',
            name='examen',
            field=models.CharField(choices=[('BEPC', 'BEPC'), ('PROBATOIRE', 'Probatoire'), ('BAC', 'BAC'), ('CAP', 'CAP'), ('GCE', 'GCE'), ('AUTRE', 'Devoir surveillé / Autre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='examen',
            field=models.CharField(choices=[('BEPC', 'BEPC'), ('PROBATOIRE', 'Probatoire'), ('BAC', 'BAC'), ('CAP', 'CAP'), ('GCE', 'GCE'), ('AUTRE', 'Devoir surveillé / Autre')], max_length=20),
        ),
    ]
