# Generated by Django 6.0.7 on 2026-09-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0056_seed_exam_sessions_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='date_fin',
            field=models.DateField(blank=True, help_text="Dernier jour de la session d'examen (calendrier officiel). Vide si pas encore connu.", null=True),
        ),
    ]
