# Generated by Django 6.0.7 on 2026-09-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0058_seed_exam_sessions_2026_date_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='cursus_recommandes',
            field=models.ManyToManyField(blank=True, help_text="Cursus auxquels ce cours est aussi SUGGÉRÉ (liens du quiz, révisions, parcours) alors qu'aucune de ses épreuves sources n'en vient - ex. un cours d'EPS tiré du BAC, valable tel quel au BEPC. Sans effet sur l'accès ni sur l'affichage, que règle `cursus` seul (voir q_cours_du_cursus).", related_name='cours_recommandes', to='catalog.cursus'),
        ),
    ]
