# Generated by Django 6.0.7 on 2026-10-10 21:50

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations

# UPPER(col) et pas la colonne brute : c'est la forme que Django émet pour __icontains sur
# Postgres (UPPER(col) LIKE UPPER(%x%)), un index sur la colonne seule ne servirait pas.
_INDEXES = [
    ("cours", "cours_titre_trgm", "titre"),
    ("cours", "cours_content_trgm", "content_markdown"),
    ("lesson", "lesson_title_trgm", "title"),
    ("lesson", "lesson_content_trgm", "content_markdown"),
]


def _index(name, field):
    return django.contrib.postgres.indexes.GinIndex(
        django.contrib.postgres.indexes.OpClass(
            django.db.models.functions.text.Upper(field), name="gin_trgm_ops",
        ),
        name=name,
    )


def creer_index(apps, schema_editor):
    # Postgres seulement : les tests tournent sur SQLite, qui ne connaît ni GIN ni gin_trgm_ops.
    if schema_editor.connection.vendor != "postgresql":
        return
    for model_name, name, field in _INDEXES:
        schema_editor.add_index(apps.get_model("catalog", model_name), _index(name, field))
    # Les métadonnées d'un index GIN neuf ne sont mises à jour que par VACUUM : sans cela le
    # planificateur surestime le coût de l'index et lui préfère un balayage séquentiel du texte
    # (~500 ms au lieu de ~50 ms sur Lesson).
    schema_editor.execute("VACUUM (ANALYZE) catalog_lesson")
    schema_editor.execute("VACUUM (ANALYZE) catalog_cours")


def supprimer_index(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    for model_name, name, field in reversed(_INDEXES):
        schema_editor.remove_index(apps.get_model("catalog", model_name), _index(name, field))


class Migration(migrations.Migration):
    # VACUUM ne s'exécute pas dans une transaction.
    atomic = False

    dependencies = [
        ('catalog', '0059_cours_cursus_recommandes'),
    ]

    operations = [
        # pg_trgm : fourni avec Postgres (module contrib), "trusted" depuis PG13 donc
        # créable par le propriétaire de la base sans être superutilisateur.
        TrigramExtension(),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(model_name=model_name, index=_index(name, field))
                for model_name, name, field in _INDEXES
            ],
            database_operations=[migrations.RunPython(creer_index, supprimer_index)],
        ),
    ]
