# Generated by Django 6.0.7 on 2026-09-26 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0054_exercise_groupes_verifies_alter_exercise_groupes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationEpreuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('exam_mode_started_at', models.DateTimeField(blank=True, null=True)),
                ('mode_papier', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('note_obtenue', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('bareme_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('score_obtenu', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('exercices_marques', models.ManyToManyField(blank=True, help_text="Exercices marqués « à revoir » par l'élève.", related_name='+', to='catalog.exercise')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='catalog.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations_epreuves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationReponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traitee_at', models.DateTimeField(blank=True, null=True)),
                ('points_obtenus', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('resultat_declare', models.CharField(blank=True, choices=[('REUSSI', 'Réussi'), ('PARTIEL', 'Partiellement réussi'), ('ECHEC', 'Échec')], max_length=10)),
                ('cause_perte', models.CharField(blank=True, choices=[('TEMPS', 'Manque de temps'), ('CONNAISSANCE', 'Notion à revoir'), ('METHODE', 'Erreur de méthode'), ('CALCUL', 'Erreur de calcul'), ('INATTENTION', "Inattention à l'énoncé")], max_length=15)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.exercise')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='simulations.simulationepreuve')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('simulation', 'exercise'), name='unique_reponse_par_exercice_et_simulation')],
            },
        ),
    ]
