# Generated by Django 6.0.7 on 2026-10-05 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0059_cours_cursus_recommandes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermeRecherche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terme', models.CharField(max_length=60, unique=True)),
                ('frequence', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'terme de recherche',
                'verbose_name_plural': 'termes de recherche',
            },
        ),
        migrations.CreateModel(
            name='RechercheSansResultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requete', models.CharField(max_length=80)),
                ('pays_code', models.CharField(max_length=10)),
                ('nb', models.PositiveIntegerField(default=1)),
                ('premiere_fois', models.DateTimeField(auto_now_add=True)),
                ('derniere_fois', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'recherche sans résultat',
                'verbose_name_plural': 'recherches sans résultat',
                'ordering': ['-nb', '-derniere_fois'],
                'constraints': [models.UniqueConstraint(fields=('requete', 'pays_code'), name='unique_recherche_vide_par_pays')],
            },
        ),
        migrations.CreateModel(
            name='EntreeRecherche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('THEME', 'Thèmes'), ('COURS', 'Cours'), ('EPREUVE', 'Épreuves'), ('INEDITE', 'Épreuves inédites'), ('EXERCICE', 'Exercices'), ('QUIZ', 'Questions de quiz')], db_index=True, max_length=10)),
                ('objet_id', models.PositiveIntegerField(help_text="Clé primaire de l'objet source : Tag (THEME), Cours, Lesson, EpreuveInedite, Exercise ou CompetenceItem.")),
                ('tous_cursus', models.BooleanField(default=False, help_text="Proposé à tout cursus (notion commune) : retenu quel que soit le filtre d'examen.")),
                ('titre', models.CharField(max_length=255)),
                ('titre_norm', models.CharField(max_length=255)),
                ('cles_norm', models.TextField()),
                ('texte_norm', models.TextField(blank=True)),
                ('apercu', models.CharField(blank=True, max_length=255)),
                ('annee', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('groupe', models.CharField(blank=True, max_length=40)),
                ('poids', models.PositiveIntegerField(default=0)),
                ('est_gratuit', models.BooleanField(default=False, help_text='Lisible sans abonnement (vitrine / épreuve offerte).')),
                ('meta', models.JSONField(blank=True, default=dict, help_text="Champs propres au type : slug, numéro d'exercice, id de thème, compteurs, cursus d'accès...")),
                ('cursus', models.ManyToManyField(blank=True, help_text="Cursus auxquels ce résultat est PROPOSÉ (pas forcément ceux de l'accès - voir meta['acces_ids']).", related_name='+', to='catalog.cursus')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.subject')),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.country')),
            ],
            options={
                'verbose_name': 'entrée de recherche',
                'verbose_name_plural': 'entrées de recherche',
                'indexes': [models.Index(fields=['pays', 'type'], name='recherche_e_pays_id_27d2c4_idx')],
                'constraints': [models.UniqueConstraint(fields=('type', 'objet_id', 'matiere'), name='unique_entree_recherche_par_objet')],
            },
        ),
    ]
