# Generated by Django 6.0.7 on 2026-10-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recherche', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='termerecherche',
            name='phonetique',
            field=models.CharField(blank=True, db_index=True, default='', max_length=60),
        ),
    ]
