# Generated by Django 6.0.7 on 2026-10-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recherche', '0002_phonetique_des_termes'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreerecherche',
            name='frequence',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entreerecherche',
            name='niveau',
            field=models.SmallIntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='entreerecherche',
            name='popularite',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
