"""
Django settings for edtech_cm project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import sys
from datetime import timedelta
from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="", cast=Csv())

# Nécessaire pour que le context processor "debug" active {% if debug %} dans les templates
# (utilisé pour pré-remplir le login admin en dev - jamais actif si DEBUG=False).
INTERNAL_IPS = ["127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "users",
    "catalog",
    "subscriptions",
    "payments",
    "access",
    "quiz",
]

AUTH_USER_MODEL = "users.User"

SMS_BACKEND = config("SMS_BACKEND", default="users.sms_backends.ConsoleSMSBackend")

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    # Multiple de 3 (grille catalogue en lg:grid-cols-3) plutôt que la valeur par
    # défaut de 20 - une page complète ne laisse jamais une rangée à moitié vide.
    "PAGE_SIZE": 24,
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=2),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "USER_ID_FIELD": "phone_number",
    "USER_ID_CLAIM": "phone_number",
}

CORS_ALLOWED_ORIGINS = config(
    "CORS_ALLOWED_ORIGINS", default="http://localhost",  cast=Csv(),
)

# Nom et domaine de la plateforme - provisoires tant que le produit est en conception,
# donc jamais codés en dur ailleurs que via ces deux réglages (voir aussi les
# variables VITE_SITE_NAME/VITE_SITE_URL côté frontend, qui doivent rester en phase).
SITE_NAME = config("SITE_NAME", default="EduKamer")
# Domaine du frontend (SPA Vite, servie séparément de cette API) - utilisé pour
# construire les URLs absolues du sitemap.xml (catalog.sitemap), qui doivent pointer
# vers les pages consultables par un visiteur, jamais vers cette API.
FRONTEND_URL = config("FRONTEND_URL", default="https://edukora.africa").rstrip("/")

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "edtech_cm.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.template.context_processors.debug",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "edtech_cm.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST", default="localhost"),
        "PORT": config("DB_PORT", default="5432"),
    }
}

# `manage.py test` a besoin de CREATE DATABASE, que le rôle applicatif Postgres
# (DB_USER) n'a délibérément pas (moindre privilège en dev comme en prod - ce n'est
# pas un oubli à corriger côté rôle Postgres). SQLite en mémoire pour les tests
# uniquement : aucune donnée, aucun rôle Postgres à toucher, et jamais utilisé par
# runserver (qui reste sur DATABASES["default"] tel que défini ci-dessus).
if "test" in sys.argv:
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": ":memory:",
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "fr-fr"

TIME_ZONE = "Africa/Douala"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
# Cible de `collectstatic` en production : Caddy sert ces fichiers directement depuis
# le volume partagé (voir docker-compose.yml), Django ne les sert jamais lui-même
# hors DEBUG.
STATIC_ROOT = BASE_DIR / "staticfiles"

# PDF de sujet (public, jamais le corrigé - voir catalog/sujet_pdf.py) : généré hors
# ligne par une commande dédiée, jamais dans le cycle de requête HTTP. Pas de
# protection d'accès nécessaire puisque le contenu est déjà public par nature.
MEDIA_URL = "media/"

STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_ROOT = BASE_DIR / "media"

# Stockage des FileField (Figure.image, Lesson.sujet_pdf - voir catalog/models.py) :
# DigitalOcean Spaces si SPACES_BUCKET est renseigné, sinon disque local (dev/tests
# sans identifiants Spaces). Ne migre pas le contenu déjà présent sur MEDIA_ROOT : ce
# contenu historique continue d'être servi tel quel par Caddy et reste résolu en
# local par sujet_pdf._resolve_media_paths (qui a besoin d'un vrai fichier disque pour
# Playwright) - seuls les NOUVEAUX fichiers partent vers Spaces à partir de ce
# changement. Une copie offsite du contenu historique est gérée séparément par le
# service "backup" (voir docker/backup/sync_media.sh), sans changer où il est servi.
SPACES_BUCKET = config("SPACES_BUCKET", default="")

if SPACES_BUCKET:
    AWS_STORAGE_BUCKET_NAME = SPACES_BUCKET
    AWS_ACCESS_KEY_ID = config("SPACES_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = config("SPACES_SECRET_ACCESS_KEY")
    AWS_S3_REGION_NAME = config("SPACES_REGION")
    AWS_S3_ENDPOINT_URL = f"https://{config('SPACES_ENDPOINT')}"
    # Domaine utilisé pour construire les URLs publiques (figure.image.url, etc.) - le
    # point de terminaison CDN Spaces si activé sur le bucket (mis en cache, plus
    # rapide), sinon l'API Spaces brute du bucket.
    AWS_S3_CUSTOM_DOMAIN = config(
        "SPACES_CDN_DOMAIN",
        default=f"{SPACES_BUCKET}.{AWS_S3_REGION_NAME}.digitaloceanspaces.com",
    )
    # Ce contenu (figures d'exercice, PDF de sujet) est déjà public par nature (voir
    # commentaire MEDIA_URL) : chaque objet public dès l'upload, pas besoin d'URLs
    # signées à durée limitée.
    AWS_DEFAULT_ACL = "public-read"
    AWS_QUERYSTRING_AUTH = False
    STORAGES = {
        "default": {"BACKEND": "storages.backends.s3.S3Storage"},
        "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
    }
else:
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
    }



# Sécurité HTTPS - actif derrière le reverse proxy Caddy en production (voir
# docker-compose.yml / Caddyfile). Dérivé de DEBUG par défaut mais surchargeable via
# l'environnement, pour pouvoir tester la stack Docker en local sans TLS sans avoir
# à réactiver DEBUG=True juste pour ça.
CSRF_TRUSTED_ORIGINS = config("CSRF_TRUSTED_ORIGINS", default="", cast=Csv())
# Caddy pose cet en-tête sur toute requête proxyée : sans ça, Django ne peut jamais
# savoir que la connexion d'origine était en HTTPS (il ne voit que du HTTP en interne
# entre Caddy et gunicorn) et request.is_secure()/CSRF/redirections se comportent
# comme si le site tournait en clair.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

SECURE_SSL_REDIRECT = config("SECURE_SSL_REDIRECT", default=not DEBUG, cast=bool)
SESSION_COOKIE_SECURE = SECURE_SSL_REDIRECT
CSRF_COOKIE_SECURE = SECURE_SSL_REDIRECT
# Démarre à 1 semaine plutôt que la valeur classique d'1 an (31536000) : HSTS est mis
# en cache par les navigateurs eux-mêmes, une erreur de config HTTPS ici n'est pas
# trivialement réversible pour les visiteurs déjà passés - à monter progressivement
# une fois le HTTPS confirmé stable en production.
SECURE_HSTS_SECONDS = config("SECURE_HSTS_SECONDS", default=604800 if SECURE_SSL_REDIRECT else 0, cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_SSL_REDIRECT
SECURE_HSTS_PRELOAD = False


LOGGING = {
    "version": 1,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "loggers": {
        "django.db.backends": {
            "handlers": ["console"],
            "level": "DEBUG",
        },
    },
}