"""
Django settings for edtech_cm project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import sys
from datetime import timedelta
from pathlib import Path
from decouple import config, Csv

import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="", cast=Csv())

# Nécessaire pour que le context processor "debug" active {% if debug %} dans les templates
# (utilisé pour pré-remplir le login admin en dev - jamais actif si DEBUG=False).
INTERNAL_IPS = ["127.0.0.1"]

# Supervision d'erreurs (Sentry) - voir l'audit UX, reco 5.1 : jusqu'ici "la seule
# remontée de bug possible est un message spontané d'un utilisateur". Inerte tant que
# SENTRY_DSN n'est pas renseigné (aucun projet Sentry n'a encore été créé pour ce
# dépôt) - sentry_sdk.init() n'est alors jamais appelé, et tout appel sentry_sdk.*
# ailleurs dans le code (voir payments/views.py, la chaîne de paiement étant la
# priorité citée dans le rapport) devient un no-op silencieux plutôt que de lever une
# erreur - sûr à laisser dans le code même avant qu'un DSN existe.
SENTRY_DSN = config("SENTRY_DSN", default="")
if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        environment=config("SENTRY_ENVIRONMENT", default="production"),
        integrations=[DjangoIntegration()],
        # Échantillon prudent par défaut (pas 1.0) : un site à trafic modeste n'a pas
        # besoin de tracer 100% des requêtes pour repérer une régression de
        # performance, et un taux plus bas laisse de la marge sur un plan Sentry
        # gratuit avant d'ajuster ce réglage consciemment.
        traces_sample_rate=config("SENTRY_TRACES_SAMPLE_RATE", default=0.2, cast=float),
        enable_logs=True,
        # False par défaut : ne jamais envoyer IP/cookies/utilisateur à un service
        # tiers sans décision explicite, sur un produit qui traite des numéros de
        # téléphone (voir users.models.User) - à activer via l'environnement plus
        # tard si besoin, jamais un choix par défaut.
        send_default_pii=config("SENTRY_SEND_DEFAULT_PII", default=False, cast=bool),
    )


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "users",
    "catalog",
    "programme",
    "subscriptions",
    "payments",
    "access",
    "quiz",
    "analytics",
    "inedit",
    "fiches",
    "whatsapp",
]

AUTH_USER_MODEL = "users.User"

SMS_BACKEND = config("SMS_BACKEND", default="users.sms_backends.ConsoleSMSBackend")
# Même patron : WHATSAPP_BACKEND reste sur le backend console (journalise au lieu
# d'envoyer) tant que WHATSAPP_ACCESS_TOKEN/WHATSAPP_PHONE_NUMBER_ID (lus directement
# via decouple dans whatsapp.backends.MetaCloudAPIBackend, pas ici) ne sont pas
# réellement configurés - voir whatsapp.backends pour le détail des deux backends.
WHATSAPP_BACKEND = config("WHATSAPP_BACKEND", default="whatsapp.backends.ConsoleWhatsAppBackend")

# Plafonds d'envoi d'OTP (voir users.otp_service.request_otp pour la mécanique). Réglages
# d'exploitation, donc lus dans l'environnement : le bon niveau dépend du trafic réel et
# du tarif SMS du fournisseur, et doit pouvoir être ajusté sans redéploiement.
#
# Volontairement large : les abonnés mobiles camerounais sortent massivement derrière le
# CGNAT de leur opérateur, donc des milliers d'utilisateurs légitimes peuvent partager
# une seule IP publique - un plafond serré ici ne bloquerait pas un attaquant seul, il
# couperait l'authentification à tous les clients MTN d'un coup. Ce plafond ne vise que
# le pumping grossier depuis une source unique ; c'est OTP_DAILY_GLOBAL_CAP qui borne
# réellement la facture. Ne pas baisser cette valeur sans avoir vérifié la distribution
# des IP dans OTPCode.
OTP_MAX_PER_IP_PER_HOUR = config("OTP_MAX_PER_IP_PER_HOUR", default=30, cast=int)
# Dernier filet, sur 24 h glissantes, toutes sources confondues. À monter délibérément à
# mesure que la base d'utilisateurs grandit : l'atteindre coupe l'authentification pour
# TOUT LE MONDE (voir OTPCapReached, journalisé en ERROR donc remonté à Sentry) - c'est
# un choix assumé de préférer une panne visible et bornée à une facture SMS illimitée.
OTP_DAILY_GLOBAL_CAP = config("OTP_DAILY_GLOBAL_CAP", default=1000, cast=int)

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    # Multiple de 3 (grille catalogue en lg:grid-cols-3) plutôt que la valeur par
    # défaut de 20 - une page complète ne laisse jamais une rangée à moitié vide.
    "PAGE_SIZE": 24,
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=2),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    # Sujet du token = la clé primaire, jamais le numéro de téléphone (ce qu'on
    # faisait jusqu'à la refonte du compte unique). Un identifiant de token doit être
    # immuable et toujours présent : le numéro n'est plus ni l'un (il se change, et un
    # numéro rendu est réattribué par l'opérateur - un token encore valide désignerait
    # alors le nouveau titulaire) ni l'autre (un compte créé via un fournisseur tiers
    # n'en a pas). Conséquence assumée au déploiement : les tokens déjà émis portent
    # l'ancienne claim et ne résolvent plus, donc une reconnexion unique pour tout le
    # monde - y compris via le refresh cookie de 30 jours.
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}

CORS_ALLOWED_ORIGINS = config(
    "CORS_ALLOWED_ORIGINS", default="http://localhost",  cast=Csv(),
)
# Le cookie httpOnly du refresh token (voir users.views._set_refresh_cookie) doit
# pouvoir être posé/relu depuis l'origine du frontend, servie sur un port/domaine
# distinct de cette API - sans credentials autorisés ici, le navigateur ignore
# silencieusement tout Set-Cookie sur une réponse cross-origin, quelle que soit la
# configuration du cookie lui-même. Sûr uniquement parce que CORS_ALLOWED_ORIGINS
# ci-dessus liste des origines explicites, jamais "*" (interdit par les navigateurs
# de toute façon dès que credentials=true est demandé).
CORS_ALLOW_CREDENTIALS = True

# Nom et domaine de la plateforme - provisoires tant que le produit est en conception,
# donc jamais codés en dur ailleurs que via ces deux réglages (voir aussi les
# variables VITE_SITE_NAME/VITE_SITE_URL côté frontend, qui doivent rester en phase).
SITE_NAME = config("SITE_NAME", default="EduKamer")

# Identifiant client OAuth Google (« Web application »), celui-là même que le
# frontend passe à Google Identity Services : les deux DOIVENT correspondre, c'est
# la claim `aud` vérifiée par users.google.verify_google_id_token qui garantit qu'un
# ID token émis pour une autre application ne peut pas ouvrir un compte Edukora.
# Aucun client_secret ici : le flux est un ID token vérifié par signature, jamais un
# échange de code côté serveur - il n'y a donc pas de secret à détenir.
# Vide par défaut : la connexion Google répond alors 503 plutôt que d'accepter
# n'importe quel jeton, ce qui est le comportement voulu tant qu'elle n'est pas
# configurée sur un environnement.
GOOGLE_CLIENT_ID = config("GOOGLE_CLIENT_ID", default="")
# Domaine du frontend (SPA Vite, servie séparément de cette API) - utilisé pour
# construire les URLs absolues du sitemap.xml (catalog.sitemap), qui doivent pointer
# vers les pages consultables par un visiteur, jamais vers cette API.
FRONTEND_URL = config("FRONTEND_URL", default="https://edukora.africa").rstrip("/")

# Envoi d'e-mails - aujourd'hui uniquement les codes de connexion (users.email_service).
#
# Console par défaut, sur le modèle de SMS_BACKEND : un développeur qui clone le dépôt
# voit le code dans son terminal et peut se connecter, sans compte chez un routeur ni
# risque d'écrire réellement à quelqu'un depuis une machine de développement. Le défaut
# de Django serait au contraire le backend SMTP pointé sur localhost, qui échoue avec
# une erreur de connexion refusée n'ayant aucun rapport visible avec la cause.
#
# Notre ConsoleEmailBackend plutôt que celui de Django : ce dernier écrit le message
# RFC-822 complet (en-têtes MIME compris), où le code se perd. Le nôtre affiche la même
# ligne compacte que le canal SMS, pour que les deux se relisent pareil dans les logs.
EMAIL_BACKEND = config("EMAIL_BACKEND", default="users.email_backends.ConsoleEmailBackend")
EMAIL_HOST = config("EMAIL_HOST", default="")
EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
# L'adresse d'expédition doit appartenir à un domaine dont les enregistrements SPF/DKIM
# autorisent le routeur configuré ci-dessus. Sans quoi les messages partent bien, mais
# atterrissent en indésirables chez Gmail - c'est-à-dire un utilisateur bloqué qui n'a
# aucun moyen de comprendre pourquoi, le pire mode de panne pour une authentification.
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default=f"{SITE_NAME} <no-reply@edukora.africa>")

# Plafonds d'envoi des codes e-mail. Séparés des plafonds OTP, et nettement plus larges :
# un e-mail ne se facture pas, ces valeurs bornent l'usage abusif (relais de spam) et non
# une dépense. Voir users.email_service.request_email_code.
EMAIL_CODE_MAX_PER_IP_PER_HOUR = config("EMAIL_CODE_MAX_PER_IP_PER_HOUR", default=60, cast=int)
EMAIL_CODE_DAILY_GLOBAL_CAP = config("EMAIL_CODE_DAILY_GLOBAL_CAP", default=5000, cast=int)

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "edtech_cm.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.template.context_processors.debug",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "edtech_cm.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST", default="localhost"),
        "PORT": config("DB_PORT", default="5432"),
    }
}

# `manage.py test` a besoin de CREATE DATABASE, que le rôle applicatif Postgres
# (DB_USER) n'a délibérément pas (moindre privilège en dev comme en prod - ce n'est
# pas un oubli à corriger côté rôle Postgres). SQLite en mémoire pour les tests
# uniquement : aucune donnée, aucun rôle Postgres à toucher, et jamais utilisé par
# runserver (qui reste sur DATABASES["default"] tel que défini ci-dessus).
if "test" in sys.argv:
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": ":memory:",
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "fr-fr"

TIME_ZONE = "Africa/Douala"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
# Cible de `collectstatic` en production : Caddy sert ces fichiers directement depuis
# le volume partagé (voir docker-compose.yml), Django ne les sert jamais lui-même
# hors DEBUG.
STATIC_ROOT = BASE_DIR / "staticfiles"

# PDF de sujet (public, jamais le corrigé - voir catalog/sujet_pdf.py) : généré hors
# ligne par une commande dédiée, jamais dans le cycle de requête HTTP. Pas de
# protection d'accès nécessaire puisque le contenu est déjà public par nature.
MEDIA_URL = "media/"

STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_ROOT = BASE_DIR / "media"

# Stockage des FileField (Figure.image, Lesson.sujet_pdf - voir catalog/models.py) :
# DigitalOcean Spaces si SPACES_BUCKET est renseigné, sinon disque local (dev/tests
# sans identifiants Spaces). Ne migre pas le contenu déjà présent sur MEDIA_ROOT : ce
# contenu historique continue d'être servi tel quel par Caddy et reste résolu en
# local par sujet_pdf._resolve_media_paths (qui a besoin d'un vrai fichier disque pour
# Playwright) - seuls les NOUVEAUX fichiers partent vers Spaces à partir de ce
# changement. Une copie offsite du contenu historique est gérée séparément par le
# service "backup" (voir docker/backup/sync_media.sh), sans changer où il est servi.
SPACES_BUCKET = config("SPACES_BUCKET", default="")

if SPACES_BUCKET:
    AWS_STORAGE_BUCKET_NAME = SPACES_BUCKET
    AWS_ACCESS_KEY_ID = config("SPACES_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = config("SPACES_SECRET_ACCESS_KEY")
    AWS_S3_REGION_NAME = config("SPACES_REGION")
    AWS_S3_ENDPOINT_URL = f"https://{config('SPACES_ENDPOINT')}"
    # Domaine utilisé pour construire les URLs publiques (figure.image.url, etc.) - le
    # point de terminaison CDN Spaces si activé sur le bucket (mis en cache, plus
    # rapide), sinon l'API Spaces brute du bucket.
    AWS_S3_CUSTOM_DOMAIN = config(
        "SPACES_CDN_DOMAIN",
        default=f"{SPACES_BUCKET}.{AWS_S3_REGION_NAME}.digitaloceanspaces.com",
    )
    # Ce contenu (figures d'exercice, PDF de sujet) est déjà public par nature (voir
    # commentaire MEDIA_URL) : chaque objet public dès l'upload, pas besoin d'URLs
    # signées à durée limitée.
    AWS_DEFAULT_ACL = "public-read"
    AWS_QUERYSTRING_AUTH = False
    STORAGES = {
        "default": {"BACKEND": "storages.backends.s3.S3Storage"},
        "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
        # PDF sujet d'Épreuve Inédite (voir inedit/sujet_pdf.py) : contrairement au
        # reste de "default" (public par nature, voir plus haut), ce contenu reste
        # payant (une épreuve jamais publiée ailleurs, même sans les réponses) -
        # jamais public-read, jamais d'URL construite côté client. Seul point de
        # sortie : inedit.views.download_sujet_pdf, gated par has_access_inedite, qui
        # lit le fichier côté serveur et le stream en réponse. Le corrigé, lui, ne
        # génère jamais de PDF (voir inedit/sujet_pdf.py, docstring de module).
        "inedit_protected": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {"default_acl": "private", "querystring_auth": True},
        },
        # PDF sujet/corrigé d'une fiche répétiteur (voir fiches/pdf.py) - même
        # raisonnement que "inedit_protected" ci-dessus (jamais public-read, jamais
        # d'URL construite côté client, seul point de sortie : fiches.views.download_*,
        # gated par ownership). Emplacement dédié plutôt que de réutiliser
        # "inedit_protected" : une fiche n'a rien à voir avec une Épreuve Inédite.
        "fiches_protected": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {"default_acl": "private", "querystring_auth": True},
        },
    }
else:
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
        # Répertoire hors MEDIA_ROOT : jamais servi par le static() de urls.py (DEBUG)
        # ni par Caddy en production - voir le commentaire "inedit_protected" ci-dessus.
        "inedit_protected": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
            "OPTIONS": {"location": str(BASE_DIR / "protected_media")},
        },
        "fiches_protected": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
            "OPTIONS": {"location": str(BASE_DIR / "protected_media" / "fiches")},
        },
    }



# Sécurité HTTPS - actif derrière le reverse proxy Caddy en production (voir
# docker-compose.yml / Caddyfile). Dérivé de DEBUG par défaut mais surchargeable via
# l'environnement, pour pouvoir tester la stack Docker en local sans TLS sans avoir
# à réactiver DEBUG=True juste pour ça.
CSRF_TRUSTED_ORIGINS = config("CSRF_TRUSTED_ORIGINS", default="", cast=Csv())
# Caddy pose cet en-tête sur toute requête proxyée : sans ça, Django ne peut jamais
# savoir que la connexion d'origine était en HTTPS (il ne voit que du HTTP en interne
# entre Caddy et gunicorn) et request.is_secure()/CSRF/redirections se comportent
# comme si le site tournait en clair.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

SECURE_SSL_REDIRECT = config("SECURE_SSL_REDIRECT", default=not DEBUG, cast=bool)
SESSION_COOKIE_SECURE = SECURE_SSL_REDIRECT
CSRF_COOKIE_SECURE = SECURE_SSL_REDIRECT
# Démarre à 1 semaine plutôt que la valeur classique d'1 an (31536000) : HSTS est mis
# en cache par les navigateurs eux-mêmes, une erreur de config HTTPS ici n'est pas
# trivialement réversible pour les visiteurs déjà passés - à monter progressivement
# une fois le HTTPS confirmé stable en production.
SECURE_HSTS_SECONDS = config("SECURE_HSTS_SECONDS", default=604800 if SECURE_SSL_REDIRECT else 0, cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_SSL_REDIRECT
SECURE_HSTS_PRELOAD = False


LOGGING = {
    "version": 1,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "loggers": {
        "django.db.backends": {
            "handlers": ["console"],
            "level": "DEBUG",
        },
    },
}