# Generated by Django 6.0.7 on 2026-08-12 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0042_seed_education_civique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(blank=True, help_text="6e, 5e, 4e, 3e, 2nde, 1ère, Tle - descriptif seulement (distingue les classes d'un même Cursus BEPC). La relation structurante reste `cursus`.", max_length=10)),
                ('serie_label', models.CharField(blank=True, help_text='Libellé de série tel qu\'écrit dans le programme source ("C-E", "D", "TI"...), vide pour le BEPC. Sert de discriminant : chaque série repart de son propre numéro de module au sein d\'une classe (ex : 1ère D et 1ère C-E ont toutes deux un "Module 21") - `numero` seul ne suffit donc pas à identifier un module.', max_length=20)),
                ('numero', models.CharField(help_text='Numéro officiel du module dans le programme (ex : "25").', max_length=10)),
                ('titre', models.CharField(max_length=255)),
                ('credit_heures', models.PositiveIntegerField(blank=True, null=True)),
                ('famille_situations', models.TextField(blank=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('cursus', models.ManyToManyField(blank=True, help_text="Vide pour une classe sans examen national (ex: 2nde) - le module reste dans le référentiel mais n'est rattaché à aucun contenu edukora pour l'instant.", related_name='modules_officiels', to='catalog.cursus')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modules_officiels', to='catalog.subject')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Savoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('intitule', models.CharField(max_length=255)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savoirs', to='programme.module')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('subject', 'classe', 'serie_label', 'numero'), name='unique_module_officiel'),
        ),
    ]
