# Generated by Django 6.0.7 on 2026-08-08 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_cours_slug_unique'),
        ('payments', '0005_mobilemoneyaccount_manualpayment'),
        ('subscriptions', '0004_parrainagerecompense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parrainagerecompense',
            name='manual_payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parrainage_recompense', to='payments.manualpayment'),
        ),
        migrations.AlterField(
            model_name='parrainagerecompense',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parrainage_recompense', to='payments.transaction'),
        ),
        migrations.AddConstraint(
            model_name='parrainagerecompense',
            constraint=models.CheckConstraint(condition=models.Q(('transaction__isnull', False), ('manual_payment__isnull', False), _connector='XOR'), name='parrainage_recompense_exactly_one_source'),
        ),
    ]
