# Generated by Django 6.0.7 on 2026-08-09 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0041_widen_question_numero"),
        ("subscriptions", "0005_parrainagerecompense_manual_payment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("ABONNEMENT", "Abonnement cursus"),
                    ("ADDON_INEDIT", "Add-on Épreuves Inédites"),
                ],
                default="ABONNEMENT",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="InscriptionInedite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cursus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inscriptions_inedites",
                        to="catalog.cursus",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscriptions_inedites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "cursus"),
                        name="unique_inscription_inedite_per_cursus",
                    )
                ],
            },
        ),
    ]
