# Generated by Django 6.0.7 on 2026-08-09 21:33

from django.db import migrations, models


# Backfill : la formule "Max" (1 an, voir subscriptions/migrations/0002_seed_plans.py)
# inclut désormais l'add-on Épreuves Inédites - couvre à la fois les Plan déjà seedés
# en base (déploiement existant) et un futur `migrate` sur une base neuve, où
# `seed_plans` (0002) tourne toujours AVANT ce champ n'existe et ne peut donc pas le
# renseigner lui-même à la création.
def backfill_inclut_inedit_pour_max(apps, schema_editor):
    Plan = apps.get_model("subscriptions", "Plan")
    Plan.objects.filter(product_type="ABONNEMENT", duration_mode="FIXE", duration_days=365).update(inclut_inedit=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_plan_product_type_inscriptioninedite'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='inclut_inedit',
            field=models.BooleanField(default=False, help_text="Un Plan ABONNEMENT qui coche ceci active aussi l'add-on Épreuves Inédites (InscriptionInedite) en plus de l'abonnement, pour la même durée - sans achat séparé d'un Plan ADDON_INEDIT. Décision produit du 2026-08-09 : la formule Max (1 an) inclut l'accès aux inédites. Sans effet sur un Plan ADDON_INEDIT lui-même (déjà exclusivement dédié à cet accès, voir _activer_acces) - n'a de sens que pour product_type=ABONNEMENT."),
        ),
        migrations.RunPython(backfill_inclut_inedit_pour_max, noop_reverse),
    ]
