# Generated by Django 6.0.7 on 2026-08-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_parrainage_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='duration_mode',
            field=models.CharField(choices=[('FIXE', 'Durée fixe'), ('JUSQUA_EXAMEN', "Jusqu'à l'examen")], default='FIXE', help_text="Palier du Plan qui a (au moins une fois) financé cette ligne - copié depuis Plan.duration_mode à l'activation (voir SubscriptionManager.activate_or_extend), jamais déduit après coup. Distinct de has_access (qui ignore ce champ, n'importe quel palier donne accès au contenu de base) : sert uniquement à gater les fonctionnalités pensées comme argument de vente propre à Jusqu'à l'Examen (voir access.services.has_access_jusqua_examen).", max_length=20),
        ),
    ]
