"""
Django settings for edtech_cm project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import sys
from datetime import timedelta
from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="", cast=Csv())

# Nécessaire pour que le context processor "debug" active {% if debug %} dans les templates
# (utilisé pour pré-remplir le login admin en dev - jamais actif si DEBUG=False).
INTERNAL_IPS = ["127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "users",
    "catalog",
    "subscriptions",
    "payments",
    "access",
]

AUTH_USER_MODEL = "users.User"

SMS_BACKEND = config("SMS_BACKEND", default="users.sms_backends.ConsoleSMSBackend")

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=2),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "USER_ID_FIELD": "phone_number",
    "USER_ID_CLAIM": "phone_number",
}

CORS_ALLOWED_ORIGINS = config(
    "CORS_ALLOWED_ORIGINS", default="http://localhost:5173", cast=Csv(),
)

# Nom et domaine de la plateforme - provisoires tant que le produit est en conception,
# donc jamais codés en dur ailleurs que via ces deux réglages (voir aussi les
# variables VITE_SITE_NAME/VITE_SITE_URL côté frontend, qui doivent rester en phase).
SITE_NAME = config("SITE_NAME", default="EduKamer")
# Domaine du frontend (SPA Vite, servie séparément de cette API) - utilisé pour
# construire les URLs absolues du sitemap.xml (catalog.sitemap), qui doivent pointer
# vers les pages consultables par un visiteur, jamais vers cette API.
FRONTEND_URL = config("FRONTEND_URL", default="https://edukamer.cm").rstrip("/")

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "edtech_cm.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.template.context_processors.debug",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "edtech_cm.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST", default="localhost"),
        "PORT": config("DB_PORT", default="5432"),
    }
}

# `manage.py test` a besoin de CREATE DATABASE, que le rôle applicatif Postgres
# (DB_USER) n'a délibérément pas (moindre privilège en dev comme en prod - ce n'est
# pas un oubli à corriger côté rôle Postgres). SQLite en mémoire pour les tests
# uniquement : aucune donnée, aucun rôle Postgres à toucher, et jamais utilisé par
# runserver (qui reste sur DATABASES["default"] tel que défini ci-dessus).
if "test" in sys.argv:
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": ":memory:",
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "fr-fr"

TIME_ZONE = "Africa/Douala"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# PDF de sujet (public, jamais le corrigé - voir catalog/sujet_pdf.py) : généré hors
# ligne par une commande dédiée, jamais dans le cycle de requête HTTP. Stockage local,
# pas de protection d'accès nécessaire puisque le contenu est déjà public par nature.
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"
