# Generated by Django 6.0.7 on 2026-08-14 09:25

import django.db.models.deletion
import fiches.models
import fiches.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0043_tag_savoir_officiel"),
        ("quiz", "0005_revisionschedule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FicheGeneree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                (
                    "difficulte",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FAIBLE", "Faible"),
                            ("MOYENNE", "Moyenne"),
                            ("ELEVEE", "Élevée"),
                        ],
                        help_text="Filtre optionnel - vide veut dire toutes difficultés confondues.",
                        max_length=10,
                    ),
                ),
                (
                    "nombre_questions",
                    models.PositiveSmallIntegerField(
                        help_text="Nombre de questions demandé par le répétiteur."
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_COURS", "Génération en cours"),
                            ("PRETE", "Prête"),
                            ("ECHEC", "Échec"),
                        ],
                        default="EN_COURS",
                        max_length=10,
                    ),
                ),
                (
                    "sujet_pdf",
                    models.FileField(
                        blank=True,
                        storage=fiches.storage.protected_storage,
                        upload_to=fiches.models._sujet_pdf_upload_to,
                    ),
                ),
                (
                    "corrige_pdf",
                    models.FileField(
                        blank=True,
                        storage=fiches.storage.protected_storage,
                        upload_to=fiches.models._corrige_pdf_upload_to,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cursus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fiches",
                        to="catalog.cursus",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fiches",
                        to="catalog.subject",
                    ),
                ),
                (
                    "themes",
                    models.ManyToManyField(
                        help_text="Compétences choisies par le répétiteur au moment de la génération.",
                        related_name="fiches",
                        to="catalog.tag",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FicheItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordre", models.PositiveSmallIntegerField()),
                (
                    "competence_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fiche_items",
                        to="quiz.competenceitem",
                    ),
                ),
                (
                    "fiche",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="fiches.fichegeneree",
                    ),
                ),
            ],
            options={
                "ordering": ["fiche", "ordre"],
            },
        ),
        migrations.AddIndex(
            model_name="fichegeneree",
            index=models.Index(
                fields=["owner", "-created_at"], name="fiches_fich_owner_i_3aba6e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="ficheitem",
            constraint=models.UniqueConstraint(
                fields=("fiche", "ordre"), name="unique_ordre_par_fiche"
            ),
        ),
    ]
