# Generated by Django 6.0.7 on 2026-08-07 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("search_no_results", "Recherche sans résultat"),
                            ("payment_initiated", "Paiement initié"),
                            ("payment_succeeded", "Paiement réussi"),
                            ("payment_failed", "Paiement échoué"),
                            ("payment_timeout", "Paiement - confirmation trop longue"),
                            ("quiz_started", "Quiz démarré"),
                            ("quiz_completed", "Quiz terminé"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("properties", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL pour un visiteur anonyme - jamais d'identifiant de remplacement inventé pour ce cas.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
