# Generated by Django 6.0.7 on 2026-08-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyticsevent",
            name="name",
            field=models.CharField(
                choices=[
                    ("search_no_results", "Recherche sans résultat"),
                    ("payment_initiated", "Paiement initié"),
                    ("payment_succeeded", "Paiement réussi"),
                    ("payment_failed", "Paiement échoué"),
                    ("payment_timeout", "Paiement - confirmation trop longue"),
                    ("quiz_started", "Quiz démarré"),
                    ("quiz_completed", "Quiz terminé"),
                    ("inedit_tentative_started", "Épreuve inédite démarrée"),
                    ("inedit_tentative_completed", "Épreuve inédite terminée"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
