# Generated by Django 6.0.7 on 2026-08-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0004_alter_analyticsevent_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyticsevent",
            name="name",
            field=models.CharField(
                choices=[
                    ("search_no_results", "Recherche sans résultat"),
                    ("payment_initiated", "Paiement initié"),
                    ("payment_succeeded", "Paiement réussi"),
                    ("payment_failed", "Paiement échoué"),
                    ("payment_timeout", "Paiement - confirmation trop longue"),
                    ("quiz_started", "Quiz démarré"),
                    ("quiz_completed", "Quiz terminé"),
                    ("inedit_tentative_started", "Épreuve inédite démarrée"),
                    ("inedit_tentative_completed", "Épreuve inédite terminée"),
                    ("pdf_sujet_landing", "Arrivée depuis le PDF sujet partagé"),
                    (
                        "pdf_sujet_inedit_landing",
                        "Arrivée depuis le PDF sujet d'une épreuve inédite",
                    ),
                    (
                        "pdf_fiche_sujet_landing",
                        "Arrivée depuis le PDF énoncé d'une fiche répétiteur",
                    ),
                    (
                        "pdf_fiche_corrige_landing",
                        "Arrivée depuis le PDF corrigé d'une fiche répétiteur",
                    ),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
