# Generated by Django 6.0.7 on 2026-10-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_habitudes_de_retour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsevent',
            name='name',
            field=models.CharField(choices=[('search_no_results', 'Recherche sans résultat'), ('recherche_lancee', 'Recherche validée'), ('recherche_resultat_clique', 'Résultat de recherche ouvert'), ('payment_initiated', 'Paiement initié'), ('payment_succeeded', 'Paiement réussi'), ('payment_failed', 'Paiement échoué'), ('payment_timeout', 'Paiement - confirmation trop longue'), ('quiz_started', 'Quiz démarré'), ('quiz_completed', 'Quiz terminé'), ('inedit_tentative_started', 'Épreuve inédite démarrée'), ('inedit_tentative_completed', 'Épreuve inédite terminée'), ('pdf_sujet_landing', 'Arrivée depuis le PDF sujet partagé'), ('pdf_sujet_inedit_landing', "Arrivée depuis le PDF sujet d'une épreuve inédite"), ('pdf_fiche_sujet_landing', "Arrivée depuis le PDF énoncé d'une fiche répétiteur"), ('pdf_fiche_corrige_landing', "Arrivée depuis le PDF corrigé d'une fiche répétiteur"), ('plan_affiche', 'Séance du jour affichée'), ('plan_seance_demarree', 'Séance du jour démarrée'), ('plan_seance_terminee', 'Séance du jour terminée'), ('plan_verrouille_clic', 'Clic sur une séance verrouillée'), ('plan_theme_ignore', 'Thème proposé ignoré'), ('objectif_matiere', 'Matière de concentration définie ou retirée'), ('examen_ressenti', "Ressenti après l'examen"), ('tarifs_vus', 'Page des tarifs consultée'), ('abonnement_ouvert', "Page d'abonnement ouverte"), ('onboarding_termine', 'Questions de bienvenue terminées'), ('simulation_demarree', "Simulation d'une annale démarrée"), ('app_ouverte', 'Accueil ouvert (nouvelle visite)'), ('quiz_abandonne', 'Quiz quitté avant la fin'), ('objectif_xp_choisi', 'Objectif quotidien choisi'), ('objectif_xp_atteint', 'Objectif quotidien atteint')], db_index=True, max_length=30),
        ),
    ]
