# Generated by Django 6.0.7 on 2026-09-23 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0004_initial'),
        ('catalog', '0054_exercise_groupes_verifies_alter_exercise_groupes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciceFait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fait_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faits', to='catalog.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices_faits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fait_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'exercise'), name='unique_exercice_fait')],
            },
        ),
    ]
