# Generated by Django 6.0.7 on 2026-09-26 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0005_exercicefait'),
        ('catalog', '0054_exercise_groupes_verifies_alter_exercise_groupes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarqueEtude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(max_length=60)),
                ('compris', models.BooleanField(default=False)),
                ('signet', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marques_etude', to='catalog.cours')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marques_etude', to='catalog.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marques_etude', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('cours__isnull', True), ('lesson__isnull', False)), models.Q(('cours__isnull', False), ('lesson__isnull', True)), _connector='OR'), name='marqueetude_exactly_one_target'), models.UniqueConstraint(condition=models.Q(('lesson__isnull', False)), fields=('user', 'lesson', 'cle'), name='unique_marque_lesson'), models.UniqueConstraint(condition=models.Q(('cours__isnull', False)), fields=('user', 'cours', 'cle'), name='unique_marque_cours')],
            },
        ),
    ]
