# Generated by Django 6.0.7 on 2026-07-26 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0025_remove_exercise_difficulte"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordre", models.PositiveSmallIntegerField()),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.question",
                    ),
                ),
            ],
            options={
                "ordering": ["session", "ordre"],
            },
        ),
        migrations.CreateModel(
            name="QuizAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reponse_choisie",
                    models.CharField(
                        blank=True,
                        help_text="Lettre choisie, uniquement si la Question est un QCM (type_reponse=QCM).",
                        max_length=10,
                    ),
                ),
                (
                    "resultat_declare",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("REUSSI", "Réussi"),
                            ("PARTIEL", "Partiellement réussi"),
                            ("ECHEC", "Échec"),
                        ],
                        help_text="Auto-déclaré par l'élève, uniquement si la Question est ouverte.",
                        max_length=10,
                    ),
                ),
                ("temps_secondes", models.PositiveIntegerField(blank=True, null=True)),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "quiz_question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer",
                        to="quiz.quizquestion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuizSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("PRATIQUE", "Pratique libre"),
                            ("DIAGNOSTIC", "Test de niveau"),
                        ],
                        max_length=10,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cursus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quiz_sessions",
                        to="catalog.cursus",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quiz_sessions",
                        to="catalog.subject",
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quiz_sessions",
                        to="catalog.tag",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quiz_questions",
                to="quiz.quizsession",
            ),
        ),
        migrations.AddConstraint(
            model_name="quizquestion",
            constraint=models.UniqueConstraint(
                fields=("session", "ordre"), name="unique_ordre_par_session"
            ),
        ),
    ]
