# Generated by Django 6.0.7 on 2026-07-26 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0025_remove_exercise_difficulte"),
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizquestion",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="catalog.question",
            ),
        ),
    ]
