# Generated by Django 6.0.7 on 2026-08-02 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0026_country_actif"),
        ("quiz", "0002_alter_quizquestion_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizquestion",
            name="question",
            field=models.ForeignKey(
                blank=True,
                help_text="Historique pré-bascule uniquement - generer_session ne peuple plus jamais ce champ.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="catalog.question",
            ),
        ),
        migrations.CreateModel(
            name="CompetenceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enonce_markdown",
                    models.TextField(
                        help_text="Rédigé pour se lire seul - jamais extrait/copié d'une épreuve source."
                    ),
                ),
                ("corrige_markdown", models.TextField()),
                (
                    "difficulte_estimee",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FAIBLE", "Faible"),
                            ("MOYENNE", "Moyenne"),
                            ("ELEVEE", "Élevée"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "type_reponse",
                    models.CharField(
                        choices=[
                            ("OUVERTE", "Réponse ouverte (auto-évaluation)"),
                            ("QCM", "Choix multiple (correction automatique)"),
                        ],
                        default="OUVERTE",
                        max_length=10,
                    ),
                ),
                (
                    "choix",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"lettre": "a", "texte": "..."}] si type_reponse=QCM, sinon vide.',
                    ),
                ),
                (
                    "reponse_correcte",
                    models.CharField(
                        blank=True,
                        help_text="Lettre correcte si type_reponse=QCM (ex : 'b'), sinon vide.",
                        max_length=10,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("VALIDE", "Validé"),
                            ("REJETE", "Rejeté"),
                        ],
                        default="BROUILLON",
                        help_text="VALIDE requis avant d'entrer dans le pool de quiz - voir quiz.services._questions_eligibles.",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cursus",
                    models.ManyToManyField(
                        help_text="Plusieurs cursus si la compétence est commune à plusieurs séries (même logique que Lesson.cursus).",
                        related_name="competence_items",
                        to="catalog.cursus",
                    ),
                ),
                (
                    "source_exercises",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Traçabilité de la technique source uniquement - jamais affiché à l'élève.",
                        related_name="competence_items_generes",
                        to="catalog.exercise",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="competence_items",
                        to="catalog.subject",
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        help_text="Compétence unique ciblée par cet item - contrairement à Question.themes (M2M), un item généré vise une seule compétence précise.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="competence_items",
                        to="catalog.tag",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="competence_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Seule source peuplée par generer_session depuis la bascule vers CompetenceItem.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="quiz.competenceitem",
            ),
        ),
        migrations.AddConstraint(
            model_name="quizquestion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("competence_item__isnull", True), ("question__isnull", False)
                    ),
                    models.Q(
                        ("competence_item__isnull", False), ("question__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="quizquestion_exactly_one_source",
            ),
        ),
        migrations.AddIndex(
            model_name="competenceitem",
            index=models.Index(fields=["statut"], name="quiz_compet_statut_1fa9b7_idx"),
        ),
    ]
