# Generated by Django 6.0.7 on 2026-08-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0029_lesson_slug_unique"),
        ("quiz", "0003_alter_quizquestion_question_competenceitem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="competenceitem",
            name="external_id",
            field=models.CharField(
                blank=True,
                help_text="Identifiant déterministe fourni par le skill concepteur-quiz-competence en mode automatisation - clé d'idempotence pour quiz.ingestion (voir la contrainte unique_competenceitem_external_id_when_set). Vide pour un item créé manuellement depuis l'admin.",
                max_length=255,
            ),
        ),
        migrations.AddConstraint(
            model_name="competenceitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id", ""), _negated=True),
                fields=("external_id",),
                name="unique_competenceitem_external_id_when_set",
            ),
        ),
    ]
