# Generated by Django 6.0.7 on 2026-08-07 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0031_lesson_est_vitrine"),
        ("quiz", "0004_competenceitem_external_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RevisionSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "palier",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Index dans LEITNER_INTERVALS_JOURS - remis à 0 à chaque échec.",
                    ),
                ),
                (
                    "due_at",
                    models.DateField(
                        help_text="Prochaine date à laquelle ce thème doit être re-proposé en révision."
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cursus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revision_schedules",
                        to="catalog.cursus",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revision_schedules",
                        to="catalog.subject",
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revision_schedules",
                        to="catalog.tag",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revision_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["due_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "cursus", "theme"),
                        name="unique_revision_schedule",
                    )
                ],
            },
        ),
    ]
