# Generated by Django 6.0.7 on 2026-09-15 09:43

import quiz.models
import quiz.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_revisionschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='corrige_pdf',
            field=models.FileField(blank=True, help_text='Énoncés + corrigé de cette session, générés à la demande - voir quiz.pdf.', storage=quiz.storage.protected_storage, upload_to=quiz.models._corrige_pdf_upload_to),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='fiche_pdf_statut',
            field=models.CharField(blank=True, choices=[('EN_COURS', 'Génération en cours'), ('PRETE', 'Prête'), ('ECHEC', 'Échec')], help_text="Vide tant qu'aucune fiche PDF n'a été demandée - voir StatutFichePdf.", max_length=10),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='sujet_pdf',
            field=models.FileField(blank=True, help_text='Énoncés seuls de cette session, générés à la demande - voir quiz.pdf.', storage=quiz.storage.protected_storage, upload_to=quiz.models._sujet_pdf_upload_to),
        ),
    ]
