# Generated by Django 6.0.7 on 2026-09-22 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0054_exercise_groupes_verifies_alter_exercise_groupes'),
        ('programme', '0001_initial'),
        ('quiz', '0006_quizsession_corrige_pdf_quizsession_fiche_pdf_statut_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeanceJournaliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Jour local de la séance - voir la docstring de la classe.')),
                ('origine', models.CharField(choices=[('REVISION_DUE', 'Révision due'), ('LECTURE_EN_COURS', 'Lecture en cours'), ('DIAGNOSTIC', 'Calibrage'), ('PARCOURS', 'Parcours')], max_length=20)),
                ('etapes', models.JSONField(default=list, help_text="Étapes de la séance, dans l'ordre - voir quiz.services._construire_etapes.")),
                ('statut', models.CharField(choices=[('PROPOSEE', 'Proposée'), ('TERMINEE', 'Terminée')], default='PROPOSEE', max_length=10)),
                ('termine_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cursus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances_journalieres', to='catalog.cursus')),
                ('savoir', models.ForeignKey(blank=True, help_text='Alternative à `theme` pour les matières dont le parcours suit le programme officiel plutôt que la fréquence des thèmes (français, philo, histoire-géo, anglais - voir SUBJECTS_PARCOURS_PAR_FREQUENCE).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances_journalieres', to='programme.savoir')),
                ('subject', models.ForeignKey(blank=True, help_text='Nul pour un calibrage, qui porte sur tout le cursus et non sur une matière.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seances_journalieres', to='catalog.subject')),
                ('theme', models.ForeignKey(blank=True, help_text='Thème travaillé, quand la séance en cible un - voir aussi `savoir`.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances_journalieres', to='catalog.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances_journalieres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'cursus', 'date'), name='unique_seance_par_jour')],
            },
        ),
    ]
