# Generated by Django 6.0.7 on 2026-09-22 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_seancejournaliere'),
    ]

    operations = [
        migrations.AddField(
            model_name='seancejournaliere',
            name='quiz_session',
            field=models.ForeignKey(blank=True, help_text="Session lancée depuis l'étape quiz de cette séance - renseignée seulement si l'élève l'ouvre réellement. Donne le score affiché en fin de séance, et déclenche sa clôture automatique (voir quiz.views.complete_session).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances', to='quiz.quizsession'),
        ),
    ]
