# Generated by Django 6.0.7 on 2026-09-23 03:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0054_exercise_groupes_verifies_alter_exercise_groupes'),
        ('programme', '0001_initial'),
        ('quiz', '0008_seancejournaliere_quiz_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seancejournaliere',
            options={'ordering': ['-date', '-ordre']},
        ),
        migrations.RemoveConstraint(
            model_name='seancejournaliere',
            name='unique_seance_par_jour',
        ),
        migrations.AddField(
            model_name='seancejournaliere',
            name='ordre',
            field=models.PositiveSmallIntegerField(default=1, help_text="Rang de la séance dans la journée. 1 pour la séance du jour ; au-delà, une séance demandée EN PLUS par l'élève qui a fini la sienne et veut continuer (voir quiz.services.seance_supplementaire). Jamais créée d'office : c'est ce qui préserve la promesse d'une seule chose à faire."),
        ),
        migrations.AddConstraint(
            model_name='seancejournaliere',
            constraint=models.UniqueConstraint(fields=('user', 'cursus', 'date', 'ordre'), name='unique_seance_par_rang_du_jour'),
        ),
    ]
