# Generated by Django 6.0.7 on 2026-09-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_seancejournaliere_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seancejournaliere',
            name='statut',
            field=models.CharField(choices=[('PROPOSEE', 'Proposée'), ('TERMINEE', 'Terminée'), ('REMPLACEE', 'Remplacée')], default='PROPOSEE', max_length=10),
        ),
    ]
