# Generated by Django 6.0.7 on 2026-09-23 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0054_exercise_groupes_verifies_alter_exercise_groupes'),
        ('quiz', '0010_alter_seancejournaliere_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='seancejournaliere',
            name='budget_minutes',
            field=models.PositiveSmallIntegerField(default=25, help_text="Temps que l'élève s'est donné aujourd'hui (voir BUDGETS_SEANCE_MINUTES). Un PLAFOND, pas une promesse : la séance affiche sa durée réelle, souvent inférieure quand le contenu manque."),
        ),
        migrations.AddField(
            model_name='seancejournaliere',
            name='cours',
            field=models.ForeignKey(blank=True, help_text="Cours retenu pour l'étape méthode. Mémorisé plutôt que recalculé : sans lui, passer la séance à 10 minutes puis revenir à 25 la perdrait, le classement qui l'avait choisi n'étant pas rejoué à chaque ajustement.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances', to='catalog.cours'),
        ),
    ]
