# Generated by Django 6.0.7 on 2026-09-25 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0054_exercise_groupes_verifies_alter_exercise_groupes'),
        ('quiz', '0011_seancejournaliere_budget_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectifMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jusqu_au', models.DateField(help_text='Dernier jour (inclus) où le plan se concentre sur cette matière.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cursus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectifs_matiere', to='catalog.cursus')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectifs_matiere', to='catalog.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectifs_matiere', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'cursus'), name='uniq_objectif_matiere_user_cursus')],
            },
        ),
    ]
