# Generated by Django 6.0.7 on 2026-09-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_objectifmatiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='seancejournaliere',
            name='etapes_ouvertes',
            field=models.JSONField(blank=True, default=list, help_text="Clés (voir quiz.services.cle_etape) des étapes cours/exercice que l'élève a ouvertes depuis la séance. Le quiz n'y figure pas : il se lit sur quiz_session. Sert à cocher les étapes et à proposer « Reprendre la séance » - jamais à valider la séance, qu'une ouverture ne prouve pas."),
        ),
    ]