# Generated by Django 6.0.7 on 2026-09-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_seancejournaliere_etapes_ouvertes'),
    ]

    operations = [
        migrations.AddField(
            model_name='competenceitem',
            name='est_vitrine',
            field=models.BooleanField(default=False, help_text="Jouable en entier sans abonnement (voir catalog.Lesson.est_vitrine, même principe) - quiz.views.start_session laisse passer une session sans abonnement actif seulement si TOUS les items du périmètre demandé (theme/savoir/subject) sont est_vitrine=True. Choisi à la main, un thème par cursus au maximum pour donner un vrai essai plutôt qu'une démo factice (voir project_gating_non_abonne_quiz_parcours) : jamais coché en masse."),
        ),
    ]
