# Generated by Django 6.0.7 on 2026-09-29 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_competenceitem_est_vitrine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisiteAccueil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut_at', models.DateTimeField(help_text='Début de la visite en cours.')),
                ('derniere_at', models.DateTimeField(help_text='Dernier appel de la visite en cours.')),
                ('precedente_at', models.DateTimeField(blank=True, help_text='Fin de la visite précédente.', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visite_accueil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
