# Generated by Django 6.0.7 on 2026-10-03 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_profil_remplace_user'),
        ('users', '0014_objectif_xp_quotidien'),
    ]

    operations = [
        migrations.CreateModel(
            name='GainXP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.DateField(db_index=True, help_text='Jour civil LOCAL du gain, voir JourXP.')),
                ('source', models.CharField(choices=[('REPONSE', 'Réponse à une question'), ('SEANCE', 'Séance du jour terminée')], max_length=10)),
                ('points', models.PositiveSmallIntegerField()),
                ('bonus_revision', models.BooleanField(default=False, help_text='Le thème était dû en révision : +BONUS_REVISION compris dans `points`.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competence_item', models.ForeignKey(blank=True, help_text="Plafond d'un gain par item et par jour (voir quiz.xp.crediter_reponse).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='quiz.competenceitem')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gains_xp', to='users.profil')),
                ('quiz_answer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gain_xp', to='quiz.quizanswer')),
                ('seance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gain_xp', to='quiz.seancejournaliere')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JourXP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.DateField()),
                ('xp', models.PositiveIntegerField(default=0)),
                ('objectif', models.PositiveSmallIntegerField()),
                ('atteint', models.BooleanField(default=False)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jours_xp', to='users.profil')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('profil', 'jour'), name='uniq_jour_xp_par_profil')],
            },
        ),
    ]
