# Generated by Django 6.0.7 on 2026-08-08 03:30

import django.core.validators
import django.db.models.deletion
import payments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_transaction_transaction_target_matches_type_and_more'),
        ('subscriptions', '0004_parrainagerecompense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileMoneyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('ORANGE', 'Orange Money'), ('MTN', 'MTN Mobile Money')], max_length=10, unique=True)),
                ('phone_number', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Le numéro doit être un numéro camerounais valide (9 chiffres, commençant par 6).', regex='^6\\d{8}$')])),
                ('account_name', models.CharField(help_text="Nom du bénéficiaire affiché à l'utilisateur.", max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'compte Mobile Money',
                'verbose_name_plural': 'comptes Mobile Money',
            },
        ),
        migrations.CreateModel(
            name='ManualPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('ORANGE', 'Orange Money'), ('MTN', 'MTN Mobile Money')], max_length=10)),
                ('amount_expected', models.PositiveIntegerField(help_text='Recalculé depuis plan.price au moment de la déclaration - jamais fourni par le client.')),
                ('amount_declared', models.PositiveIntegerField(help_text="Montant que l'utilisateur affirme avoir payé.")),
                ('payer_phone_number', models.CharField(help_text='Numéro ayant réellement effectué le paiement (peut différer du compte Edukora du payeur).', max_length=9, validators=[django.core.validators.RegexValidator(message='Le numéro doit être un numéro camerounais valide (9 chiffres, commençant par 6).', regex='^6\\d{8}$')])),
                ('transaction_reference', models.CharField(help_text='Référence/numéro de transaction Mobile Money, normalisée (majuscules, sans espaces).', max_length=100)),
                ('paid_at', models.DateTimeField(blank=True, help_text="Date/heure du paiement déclarée par l'utilisateur.", null=True)),
                ('proof', models.FileField(blank=True, help_text="Capture d'écran optionnelle du SMS de confirmation - jamais une preuve fiable à elle seule, la validation reste administrative.", null=True, upload_to=payments.models._manual_payment_proof_path)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Validé'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=10)),
                ('rejection_reason', models.CharField(blank=True, choices=[('TRANSACTION_INTROUVABLE', 'Transaction introuvable'), ('MONTANT_INCORRECT', 'Montant incorrect'), ('TRANSACTION_DEJA_UTILISEE', 'Transaction déjà utilisée'), ('MAUVAIS_OPERATEUR', 'Mauvais opérateur'), ('PAIEMENT_NON_RECU', 'Paiement non reçu'), ('INFORMATIONS_INCOHERENTES', 'Informations incohérentes'), ('AUTRE', 'Autre')], max_length=30)),
                ('admin_comment', models.TextField(blank=True, help_text="Note interne libre de l'administrateur.")),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('declared_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_payments', to='subscriptions.plan')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_payments_reviewed', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, help_text="Renseigné une fois le paiement approuvé et l'abonnement activé/prolongé.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_payments', to='subscriptions.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='payments_ma_status_cb5faa_idx'), models.Index(fields=['transaction_reference'], name='payments_ma_transac_8d9600_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'APPROVED'])), fields=('operator', 'transaction_reference'), name='unique_active_manual_payment_reference_per_operator')],
            },
        ),
    ]
