# Generated by Django 6.0.7 on 2026-08-09 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_mobilemoneyaccount_manualpayment"),
        ("subscriptions", "0006_plan_product_type_inscriptioninedite"),
    ]

    operations = [
        migrations.AddField(
            model_name="manualpayment",
            name="inscription_inedite",
            field=models.ForeignKey(
                blank=True,
                help_text="Renseigné une fois un paiement de Plan ADDON_INEDIT approuvé - exclusif avec `subscription`.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manual_payments",
                to="subscriptions.inscriptioninedite",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="inscription_inedite",
            field=models.ForeignKey(
                blank=True,
                help_text="Renseigné une fois le paiement d'un Plan ADDON_INEDIT confirmé - exclusif avec `subscription` (voir _activer_acces).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="subscriptions.inscriptioninedite",
            ),
        ),
        migrations.AlterField(
            model_name="manualpayment",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                help_text="Renseigné une fois un paiement de Plan ABONNEMENT approuvé et l'abonnement activé/prolongé.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manual_payments",
                to="subscriptions.subscription",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                help_text="Renseigné une fois le paiement d'un Plan ABONNEMENT confirmé et l'abonnement activé/prolongé.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="subscriptions.subscription",
            ),
        ),
    ]
