# Generated by Django 6.0.7 on 2026-08-14 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_manualpayment_inscription_inedite_and_more"),
        ("subscriptions", "0008_alter_plan_product_type_inscriptionrepetiteur"),
    ]

    operations = [
        migrations.AddField(
            model_name="manualpayment",
            name="inscription_repetiteur",
            field=models.ForeignKey(
                blank=True,
                help_text="Renseigné une fois un paiement de Plan ADDON_REPETITEUR approuvé - exclusif avec `subscription`.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manual_payments",
                to="subscriptions.inscriptionrepetiteur",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="inscription_repetiteur",
            field=models.ForeignKey(
                blank=True,
                help_text="Renseigné une fois le paiement d'un Plan ADDON_REPETITEUR confirmé - exclusif avec `subscription` (voir _activer_acces).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="subscriptions.inscriptionrepetiteur",
            ),
        ),
    ]
