# Generated by Django 6.0.7 on 2026-09-26 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelanceEnvoyee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('rappel_seance', 'Rappel de la séance du jour'), ('paiement_abandonne_1', 'Paiement non abouti - premier message'), ('paiement_abandonne_2', 'Paiement non abouti - dernier message')], max_length=30)),
                ('reference', models.CharField(max_length=40)),
                ('canal', models.CharField(choices=[('email', 'E-mail')], default='email', max_length=10)),
                ('envoyee_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-envoyee_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'type', 'reference', 'canal'), name='unique_relance_par_objet')],
            },
        ),
    ]
