# Generated by Django 6.0.7 on 2026-10-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relances', '0002_abonnement_push'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relanceenvoyee',
            name='type',
            field=models.CharField(choices=[('rappel_seance', 'Rappel de la séance du jour'), ('paiement_abandonne_1', 'Paiement non abouti - premier message'), ('paiement_abandonne_2', 'Paiement non abouti - dernier message'), ('bilan_parent', 'Bilan de la semaine au parent')], max_length=30),
        ),
    ]
