# Generated by Django 6.0.7 on 2026-07-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_seed_plans"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="duration_mode",
            field=models.CharField(
                choices=[("FIXE", "Durée fixe"), ("JUSQUA_EXAMEN", "Jusqu'à l'examen")],
                default="FIXE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="duration_days",
            field=models.PositiveSmallIntegerField(
                default=30,
                help_text="Utilisé tel quel si duration_mode=FIXE. Ignoré (valeur de repli seulement, voir effective_duration_days) si duration_mode=JUSQUA_EXAMEN.",
            ),
        ),
    ]
