# Generated by Django 6.0.7 on 2026-07-19 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0017_examsession"),
        (
            "payments",
            "0004_remove_transaction_transaction_target_matches_type_and_more",
        ),
        ("subscriptions", "0003_plan_duration_mode_alter_plan_duration_days"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ParrainageRecompense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jours_offerts", models.PositiveSmallIntegerField(default=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cursus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.cursus"
                    ),
                ),
                (
                    "filleul",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parrainage_recompense",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parrain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parrainages_recompenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parrainage_recompense",
                        to="payments.transaction",
                    ),
                ),
            ],
        ),
    ]
