# Generated by Django 6.0.7 on 2026-07-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="series",
            name="code",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
