# Generated by Django 6.0.7 on 2026-07-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_series_options"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="exercise",
            constraint=models.UniqueConstraint(
                fields=("lesson", "numero_exercice"), name="unique_exercice_par_lesson"
            ),
        ),
    ]
