# Generated by Django 6.0.7 on 2026-07-16 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_remove_lesson_file_key_remove_lesson_pdf_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        help_text="cours_id fourni par correction-experte (ex. cours-resolution-equations-second-degre-...) - sert de clé d'idempotence.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("sous_theme", models.CharField(blank=True, max_length=255)),
                (
                    "duree_estimee_min",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "sections_raw",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Sections structurées telles que fournies par correction-experte (mode cours), conservées pour un rendu plus riche ultérieur.",
                    ),
                ),
                (
                    "content_markdown",
                    models.TextField(
                        blank=True,
                        help_text="Rendu Markdown aplati des sections, généré par compile_from_sections().",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("VALIDE", "Validé"),
                            ("REJETE", "Rejeté"),
                        ],
                        default="BROUILLON",
                        max_length=10,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cursus",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Vide = notion commune à toutes les séries, accessible à tout abonné actif quel que soit son cursus.",
                        related_name="cours",
                        to="catalog.cursus",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cours",
                        to="catalog.subject",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="cours", to="catalog.tag"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "cours",
                "ordering": ["titre"],
            },
        ),
        migrations.CreateModel(
            name="RappelDeMethode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        help_text="id fourni par correction-experte (ex. rdm-<epreuve>-ex<numero>-<index>) - sert de clé d'idempotence et de référence pour le mode cours.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("competence", models.CharField(max_length=255)),
                ("contenu_markdown", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cours",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rappels_source",
                        to="catalog.cours",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rappels_de_methode",
                        to="catalog.exercise",
                    ),
                ),
            ],
            options={
                "ordering": ["exercise", "external_id"],
            },
        ),
    ]
