# Generated by Django 6.0.7 on 2026-07-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_lesson_sujet_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="sujet_pdf",
            field=models.FileField(
                blank=True,
                default="",
                help_text="PDF brandé du sujet (énoncés uniquement, jamais le corrigé) - support marketing librement partageable. Généré hors ligne, jamais à la volée : voir la commande `generate_sujet_pdfs` ou l'action admin correspondante.",
                upload_to="sujets_pdf/",
            ),
            preserve_default=False,
        ),
    ]
