# Generated by Django 6.0.7 on 2026-08-09 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0041_widen_question_numero"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Blueprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="Identifiant déterministe fourni par la skill de conception en mode automatisation - clé d'idempotence pour une future inedit.ingestion (voir la contrainte unique_blueprint_external_id_when_set, même patron que CompetenceItem.external_id). Vide pour un blueprint créé manuellement depuis l'admin.",
                        max_length=255,
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                (
                    "sections_plan",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Structure de l'épreuve (nombre d'exercices, points et compétences par section, difficulté visée) - format affiné à l'usage par la future skill de conception, pas figé ici (voir catalog.models.Cours.sections_raw pour le même choix de rester en JSON libre plutôt qu'un schéma relationnel rigide).",
                    ),
                ),
                (
                    "duree_minutes",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "bareme_total",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Total des points, ex. 20.", null=True
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("VALIDE", "Validé"),
                            ("REJETE", "Rejeté"),
                        ],
                        default="BROUILLON",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "competences",
                    models.ManyToManyField(
                        help_text="Compétences visées par l'épreuve - au moins une, jamais déduites après coup depuis le contenu généré.",
                        related_name="blueprints",
                        to="catalog.tag",
                    ),
                ),
                (
                    "cursus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="blueprints",
                        to="catalog.cursus",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="blueprints",
                        to="catalog.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EpreuveInedite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="Clé d'idempotence pour une future inedit.ingestion - même rôle que Blueprint.external_id.",
                        max_length=255,
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("enonce_markdown", models.TextField(blank=True)),
                ("corrige_markdown", models.TextField(blank=True)),
                (
                    "score_originalite",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Score 0-100, calculé lors du contrôle qualité (phase pipeline) - null tant que non évalué.",
                        null=True,
                    ),
                ),
                (
                    "score_qualite",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Score 0-100, calculé lors du contrôle qualité (phase pipeline) - null tant que non évalué.",
                        null=True,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("VALIDE", "Validé"),
                            ("REJETE", "Rejeté"),
                        ],
                        default="BROUILLON",
                        max_length=10,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "blueprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="epreuves",
                        to="inedit.blueprint",
                    ),
                ),
                (
                    "cursus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="epreuves_inedites",
                        to="catalog.cursus",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="epreuves_inedites",
                        to="catalog.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExerciceInedite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_exercice", models.CharField(max_length=30)),
                ("points", models.CharField(blank=True, max_length=20)),
                (
                    "epreuve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercices",
                        to="inedit.epreuveinedite",
                    ),
                ),
            ],
            options={
                "ordering": ["epreuve", "numero_exercice"],
            },
        ),
        migrations.CreateModel(
            name="QuestionInedite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=20)),
                (
                    "ordre",
                    models.PositiveSmallIntegerField(
                        help_text="Ordre d'affichage/résolution au sein de l'exercice."
                    ),
                ),
                ("enonce_markdown", models.TextField()),
                ("corrige_markdown", models.TextField()),
                (
                    "difficulte_estimee",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FAIBLE", "Faible"),
                            ("MOYENNE", "Moyenne"),
                            ("ELEVEE", "Élevée"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "type_reponse",
                    models.CharField(
                        choices=[
                            ("OUVERTE", "Réponse ouverte (auto-évaluation)"),
                            ("QCM", "Choix multiple (correction automatique)"),
                        ],
                        default="OUVERTE",
                        max_length=10,
                    ),
                ),
                (
                    "choix",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"lettre": "a", "texte": "..."}] si type_reponse=QCM, sinon vide.',
                    ),
                ),
                (
                    "reponse_correcte",
                    models.CharField(
                        blank=True,
                        help_text="Lettre correcte si type_reponse=QCM (ex : 'b'), sinon vide.",
                        max_length=10,
                    ),
                ),
                (
                    "exercice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="inedit.exerciceinedite",
                    ),
                ),
            ],
            options={
                "ordering": ["exercice", "ordre"],
            },
        ),
        migrations.CreateModel(
            name="TentativeInedite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "score_obtenu",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Sur Blueprint.bareme_total - null tant que la tentative n'est pas soumise.",
                        null=True,
                    ),
                ),
                (
                    "epreuve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tentatives",
                        to="inedit.epreuveinedite",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tentatives_inedites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="TentativeReponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reponse_choisie",
                    models.CharField(
                        blank=True,
                        help_text="Lettre choisie, uniquement si QuestionInedite.type_reponse=QCM.",
                        max_length=10,
                    ),
                ),
                (
                    "resultat_declare",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("REUSSI", "Réussi"),
                            ("PARTIEL", "Partiellement réussi"),
                            ("ECHEC", "Échec"),
                        ],
                        help_text="Auto-déclaré par l'élève après avoir vu le corrigé, uniquement si la question est ouverte.",
                        max_length=10,
                    ),
                ),
                ("temps_secondes", models.PositiveIntegerField(blank=True, null=True)),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="inedit.questioninedite",
                    ),
                ),
                (
                    "tentative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reponses",
                        to="inedit.tentativeinedite",
                    ),
                ),
            ],
            options={
                "ordering": ["tentative", "question__ordre"],
            },
        ),
        migrations.AddIndex(
            model_name="blueprint",
            index=models.Index(fields=["statut"], name="inedit_blue_statut_d7d374_idx"),
        ),
        migrations.AddConstraint(
            model_name="blueprint",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id", ""), _negated=True),
                fields=("external_id",),
                name="unique_blueprint_external_id_when_set",
            ),
        ),
        migrations.AddIndex(
            model_name="epreuveinedite",
            index=models.Index(fields=["statut"], name="inedit_epre_statut_71010c_idx"),
        ),
        migrations.AddConstraint(
            model_name="epreuveinedite",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id", ""), _negated=True),
                fields=("external_id",),
                name="unique_epreuveinedite_external_id_when_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="exerciceinedite",
            constraint=models.UniqueConstraint(
                fields=("epreuve", "numero_exercice"),
                name="unique_exerciceinedite_par_epreuve",
            ),
        ),
        migrations.AddConstraint(
            model_name="questioninedite",
            constraint=models.UniqueConstraint(
                fields=("exercice", "numero"),
                name="unique_questioninedite_par_exercice",
            ),
        ),
        migrations.AddConstraint(
            model_name="tentativereponse",
            constraint=models.UniqueConstraint(
                fields=("tentative", "question"),
                name="unique_reponse_par_question_et_tentative",
            ),
        ),
    ]
