# Generated by Django 6.0.7 on 2026-08-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0041_widen_question_numero"),
        ("inedit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questioninedite",
            name="themes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Compétence(s) réellement testées par cette question précise - sous-ensemble des Blueprint.competences visées. Optionnel par question, mais nécessaire au calcul de score_qualite (couverture des compétences visées, voir inedit.quality.score_qualite) : une question non taguée ne compte pour aucune compétence, jamais devinée depuis son contenu.",
                related_name="questions_inedites_as_theme",
                to="catalog.tag",
            ),
        ),
    ]
