# Generated by Django 6.0.7 on 2026-08-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inedit", "0002_questioninedite_themes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tentativeinedite",
            name="score_obtenu",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Pourcentage de bonnes réponses parmi les questions répondues (0-100, même échelle que EpreuveInedite.score_originalite/score_qualite - pas une note sur Blueprint.bareme_total, non fiable à sommer depuis ExerciceInedite.points qui reste un texte libre). Null tant que la tentative n'est pas soumise.",
                null=True,
            ),
        ),
    ]
