# Generated by Django 6.0.7 on 2026-08-09 20:49

import inedit.models
import inedit.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inedit", "0003_alter_tentativeinedite_score_obtenu"),
    ]

    operations = [
        migrations.AddField(
            model_name="epreuveinedite",
            name="corrige_pdf",
            field=models.FileField(
                blank=True,
                help_text="Généré hors ligne (voir inedit.corrige_pdf.save_corrige_pdf), jamais dans le cycle d'une requête HTTP - même contrainte que catalog.sujet_pdf. Stocké sur un storage PRIVÉ (voir inedit.storage.protected_storage) : contrairement à Lesson.sujet_pdf, ce contenu EST le produit payant - jamais d'URL publique, seul point de sortie inedit.views.download_corrige_pdf (gated has_access_inedite).",
                storage=inedit.storage.protected_storage,
                upload_to=inedit.models._corrige_pdf_upload_to,
            ),
        ),
    ]
