# Generated by Django 6.0.7 on 2026-08-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inedit", "0004_epreuveinedite_corrige_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="tentativeinedite",
            name="exam_mode_started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Renseigné uniquement si l'élève a explicitement activé le mode examen (chronométré) - distinct de started_at (création de la tentative). Null pendant toute la tentative = mode libre non chronométré : le corrigé y est toujours disponible (voir _correction_disponible), aucune pression temporelle à protéger.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tentativeinedite",
            name="questions_marquees",
            field=models.ManyToManyField(
                blank=True,
                help_text="Questions marquées « à revoir » par l'élève - indépendant d'avoir répondu ou non.",
                related_name="+",
                to="inedit.questioninedite",
            ),
        ),
    ]
