# Generated by Django 6.0.7 on 2026-08-11 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0041_widen_question_numero"),
        ("inedit", "0005_tentativeinedite_exam_mode_started_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RappelDeMethodeInedite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        help_text="id fourni par concepteur-epreuve-inedite (ex. rdi-<epreuve>-ex<numero>-<index>, préfixe rdi- pour rester visuellement distinct du rdm- classique dans les logs) - sert de clé d'idempotence et de référence pour le mode cours.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("competence", models.CharField(max_length=255)),
                ("contenu_markdown", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cours",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rappels_source_inedit",
                        to="catalog.cours",
                    ),
                ),
                (
                    "exercice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rappels_de_methode",
                        to="inedit.exerciceinedite",
                    ),
                ),
            ],
            options={
                "ordering": ["exercice", "external_id"],
            },
        ),
    ]
