# Generated by Django 6.0.7 on 2026-08-11 06:30

import inedit.models
import inedit.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inedit", "0006_rappeldemethodeinedite"),
    ]

    operations = [
        migrations.AddField(
            model_name="epreuveinedite",
            name="sujet_pdf",
            field=models.FileField(
                blank=True,
                help_text="Généré hors ligne (voir inedit.sujet_pdf.save_sujet_pdf), même contrainte que corrige_pdf. Storage PRIVÉ lui aussi (contrairement à Lesson.sujet_pdf, public) : une épreuve inédite jamais publiée ailleurs reste un contenu payant même sans les réponses. Seul point de sortie inedit.views.download_sujet_pdf (gated has_access_inedite). Proposé sur la fiche épreuve (avant tentative) - voir corrige_pdf pour le pendant proposé après coup.",
                storage=inedit.storage.protected_storage,
                upload_to=inedit.models._sujet_pdf_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="epreuveinedite",
            name="corrige_pdf",
            field=models.FileField(
                blank=True,
                help_text="Généré hors ligne (voir inedit.corrige_pdf.save_corrige_pdf), jamais dans le cycle d'une requête HTTP - même contrainte que catalog.sujet_pdf. Stocké sur un storage PRIVÉ (voir inedit.storage.protected_storage) : contrairement à Lesson.sujet_pdf, ce contenu EST le produit payant - jamais d'URL publique, seul point de sortie inedit.views.download_corrige_pdf (gated has_access_inedite). Proposé à l'élève seulement APRÈS sa tentative (voir InediteResultPage.tsx) - jamais depuis la fiche épreuve, qui donnerait les réponses avant même de commencer (voir sujet_pdf pour le téléchargement proposé là).",
                storage=inedit.storage.protected_storage,
                upload_to=inedit.models._corrige_pdf_upload_to,
            ),
        ),
    ]
