# Generated by Django 6.0.7 on 2026-08-12 08:28, hand-édité : ajouter un champ unique
# directement (comme makemigrations le propose par défaut) collisionne dès l'ALTER TABLE
# si plusieurs EpreuveInedite existent déjà (toutes héritent du même slug="" par défaut) -
# voir la même contrainte que catalog.migrations pour Lesson.slug/Cours.slug en leur temps
# (voir catalog/migrations/0027_lesson_slug.py + 0028_backfill_lesson_slug.py +
# 0029_lesson_slug_unique.py, le même motif en 3 fichiers séparés plutôt qu'un seul ici).
#
# Deux étapes : 1) champ ajouté sans contrainte d'unicité + backfill ligne par ligne
# (logique de generate_unique_slug réimplémentée ici, jamais importée depuis le code vivant -
# convention déjà suivie ailleurs dans ce dépôt, voir subscriptions/migrations/0002_seed_plans.py) ;
# 2) contrainte d'unicité posée une fois toutes les lignes renseignées, via
# AddUniqueSlugConstraint plutôt qu'un simple migrations.AlterField(unique=True) : voir
# sa docstring - migrations.AlterField seul reproduit de façon fiable un
# ProgrammingError "already exists" sur Postgres (Django 6.0.7), y compris sur une base
# de test vierge sans concurrence ni ligne existante - vraisemblablement une régression
# du schema editor Postgres, introduite après que 0029_lesson_slug_unique.py (même
# opération, pour Lesson.slug) ait déjà été appliquée avec succès et enregistrée comme
# telle sur les bases existantes (jamais rejouée depuis, donc jamais retombée dessus).

from django.db import migrations, models
from django.utils.text import slugify


def backfill_slugs(apps, schema_editor):
    EpreuveInedite = apps.get_model("inedit", "EpreuveInedite")
    for epreuve in EpreuveInedite.objects.filter(slug=""):
        base = slugify(epreuve.titre) or "epreuve-inedite"
        slug = base
        counter = 2
        while EpreuveInedite.objects.filter(slug=slug).exclude(pk=epreuve.pk).exists():
            slug = f"{base}-{counter}"
            counter += 1
        epreuve.slug = slug
        epreuve.save(update_fields=["slug"])


def noop_reverse(apps, schema_editor):
    pass


class AddUniqueSlugConstraint(migrations.AlterField):
    """AlterField(unique=True) standard sur SQLite (utilisé par la suite de tests, voir
    settings.DATABASES) - le schema editor s'y comporte normalement. Sur Postgres,
    contourne un bug constaté du schema editor Django 6.0.7 : la transition
    non-unique -> unique d'un SlugField lui fait émettre deux fois le même
    "CREATE INDEX ..._like", provoquant un ProgrammingError "already exists" qui fait
    échouer toute la migration (reproduit sur une base neuve, sans aucune ligne ni
    concurrence - pas une histoire de données existantes ni de course). ADD CONSTRAINT
    brut crée la même contrainte/le même index unique sans jamais passer par ce chemin
    de code défaillant - seul l'index annexe "_like" (LIKE 'prefixe%', jamais utilisé
    pour une recherche par égalité exacte comme .filter(slug=...)) n'est pas recréé,
    sans conséquence fonctionnelle ici."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor != "postgresql":
            super().database_forwards(app_label, schema_editor, from_state, to_state)
            return
        table = to_state.apps.get_model(app_label, self.model_name)._meta.db_table
        schema_editor.execute(f"ALTER TABLE {table} ADD CONSTRAINT {table}_slug_key UNIQUE (slug)")

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor != "postgresql":
            super().database_backwards(app_label, schema_editor, from_state, to_state)
            return
        table = from_state.apps.get_model(app_label, self.model_name)._meta.db_table
        schema_editor.execute(f"ALTER TABLE {table} DROP CONSTRAINT {table}_slug_key")


class Migration(migrations.Migration):

    dependencies = [
        ("inedit", "0007_epreuveinedite_sujet_pdf_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="epreuveinedite",
            name="slug",
            field=models.SlugField(
                blank=True,
                default="",
                help_text="Généré automatiquement depuis le titre à la création - ne pas modifier après publication. Même mécanisme que catalog.models.Lesson.slug/Cours.slug (voir generate_unique_slug) : un id numérique dans l'URL ('/epreuves-inedites/6') ne dit rien du contenu et n'incite pas au partage. L'ancien lien par id reste résolu en lecture (voir inedit.views.epreuve_inedite_detail) pour ne pas casser les liens déjà partagés avant l'introduction de ce champ.",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(backfill_slugs, noop_reverse),
        AddUniqueSlugConstraint(
            model_name="epreuveinedite",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Généré automatiquement depuis le titre à la création - ne pas modifier après publication. Même mécanisme que catalog.models.Lesson.slug/Cours.slug (voir generate_unique_slug) : un id numérique dans l'URL ('/epreuves-inedites/6') ne dit rien du contenu et n'incite pas au partage. L'ancien lien par id reste résolu en lecture (voir inedit.views.epreuve_inedite_detail) pour ne pas casser les liens déjà partagés avant l'introduction de ce champ.",
                max_length=255,
                unique=True,
            ),
        ),
    ]
