# Generated by Django 6.0.7 on 2026-08-12 11:07

import inedit.models
import inedit.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inedit", "0008_epreuveinedite_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="epreuveinedite",
            name="corrige_pdf",
        ),
        migrations.AlterField(
            model_name="epreuveinedite",
            name="sujet_pdf",
            field=models.FileField(
                blank=True,
                help_text="Généré hors ligne (voir inedit.sujet_pdf.save_sujet_pdf), jamais dans le cycle d'une requête HTTP - même contrainte que catalog.sujet_pdf. Storage PRIVÉ (contrairement à Lesson.sujet_pdf, public) : une épreuve inédite jamais publiée ailleurs reste un contenu payant même sans les réponses. Seul point de sortie inedit.views.download_sujet_pdf (gated has_access_inedite). Le corrigé, lui, ne génère jamais de PDF - voir QuestionInedite.corrige_markdown/reveal_corrige, consulté uniquement en ligne, question par question, après tentative.",
                storage=inedit.storage.protected_storage,
                upload_to=inedit.models._sujet_pdf_upload_to,
            ),
        ),
    ]
