# Generated by Django 6.0.7 on 2026-08-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inedit", "0010_blueprint_epreuveinedite_cursus_m2m"),
    ]

    operations = [
        migrations.AddField(
            model_name="exerciceinedite",
            name="enonce_intro_markdown",
            field=models.TextField(
                blank=True,
                help_text="Support commun à toutes les questions de l'exercice (document à exploiter, tableau de résultats expérimentaux, données chiffrées, consigne partagée), affiché avant la première question. Même rôle que catalog.Exercise.enonce_intro_markdown, mais ici c'est le SEUL endroit où un support partagé peut vivre : le lecteur d'une tentative aplatit les exercices en une liste de questions rendues chacune depuis son propre enonce_markdown (voir InediteTentativePage.tsx) - sans ce champ, un document exploité par quatre questions devrait être recopié dans les quatre. Vide pour la plupart des exercices ; indispensable en SVT, bâtie sur l'exploitation de documents (voir le SKILL.md de concepteur-epreuve-inedite). Aucune image possible ici : la verticale inédite n'a pas d'équivalent de catalog.Figure (rien à extraire, le contenu est généré et non transcrit d'un PDF réel), donc un support doit être entièrement textuel ou tabulaire.",
            ),
        ),
    ]
