# Generated by Django 6.0.7 on 2026-08-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inedit', '0011_exerciceinedite_enonce_intro_markdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciceinedite',
            name='groupes',
            field=models.JSONField(blank=True, default=list, help_text="Pile ordonnée des repères de groupe (Partie/section/matière) portés par cet exercice, renseignée directement par la skill de conception - même rôle que catalog.Exercise.groupes, mais ici pas de repli par analyse de texte : une épreuve inédite est générée, pas transcrite, donc rien à deviner depuis un en-tête d'énoncé. Vide pour la grande majorité des épreuves (structure plate)."),
        ),
    ]
