# Generated by Django 6.0.7 on 2026-08-31 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inedit', '0012_exerciceinedite_groupes'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioninedite',
            name='groupe_local',
            field=models.CharField(blank=True, help_text='Repère de sous-partie affiché juste au-dessus de CETTE question, quand il diffère de celui de la question précédente (ex. "A-I. Vérification des savoirs (4 pts)"). Une seule étiquette plate, pas une pile comme ExerciceInedite.groupes : sert à scinder un exercice en sous-sections successives sans créer un ExerciceInedite par sous-section (voir InediteTentativePage.tsx). Ne PAS recopier ce texte dans enonce_intro_markdown, qui s\'affiche une seule fois en tête de tout l\'exercice - le mélange des deux fait apparaître toutes les sous-parties d\'un coup avant la première question. Vide pour la grande majorité des questions.', max_length=255),
        ),
    ]
