# Generated by Django 6.0.7 on 2026-09-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inedit', '0014_notation_sur_bareme'),
    ]

    operations = [
        migrations.AddField(
            model_name='tentativeinedite',
            name='mode_papier',
            field=models.BooleanField(default=False, help_text="Épreuve composée sur papier (sujet PDF imprimé), chronométrée comme un examen : l'écran ne montre que le chrono et la liste des questions à déclarer traitées, jamais les énoncés. Décidé au lancement du mode examen, jamais après."),
        ),
    ]
