# Generated by Django 6.0.7 on 2026-09-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inedit', '0015_mode_papier'),
    ]

    operations = [
        migrations.AddField(
            model_name='tentativereponse',
            name='cause_perte',
            field=models.CharField(blank=True, choices=[('TEMPS', 'Manque de temps'), ('CONNAISSANCE', 'Notion à revoir'), ('METHODE', 'Erreur de méthode'), ('CALCUL', 'Erreur de calcul'), ('INATTENTION', "Inattention à l'énoncé")], help_text="Pourquoi des points ont été perdus sur cette question, déclaré par l'élève après le corrigé (voir CausePerte). Vide : non précisé - jamais deviné.", max_length=15),
        ),
    ]
