# Generated by Django 6.0.7 on 2026-10-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inedit', '0018_titre_epreuve_inedite'),
    ]

    operations = [
        migrations.AddField(
            model_name='epreuveinedite',
            name='est_gratuite',
            field=models.BooleanField(default=False, help_text="Épreuve offerte : tout compte connecté peut la passer en entier (chrono, notation, rapport de fin), sans abonnement. Sert de vitrine - un visiteur n'achète pas un chrono qu'il n'a jamais lancé. Un COMPTE reste requis (la copie est rattachée à un profil) : c'est aussi la première inscription. Voir access.has_access_inedite. Décision éditoriale : une par cursus suffit."),
        ),
    ]
