# Generated by Django 6.0.7 on 2026-07-16 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0002_lessonunlock"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="downloadlog",
            name="access_down_lesson__953bf9_idx",
        ),
        migrations.RemoveConstraint(
            model_name="lessonunlock",
            name="unique_unlock_par_user_lesson",
        ),
        migrations.RemoveField(
            model_name="lessonunlock",
            name="lesson",
        ),
        migrations.RemoveField(
            model_name="lessonunlock",
            name="user",
        ),
        migrations.DeleteModel(
            name="DownloadLog",
        ),
        migrations.DeleteModel(
            name="LessonUnlock",
        ),
    ]
