# Generated by Django 6.0.7 on 2026-07-17 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("access", "0003_remove_downloadlog_access_down_lesson__953bf9_idx_and_more"),
        ("catalog", "0010_cours_rappeldemethode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LectureProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_read_at", models.DateTimeField(auto_now_add=True)),
                ("last_read_at", models.DateTimeField(auto_now=True)),
                (
                    "cours",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lectures",
                        to="catalog.cours",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lectures",
                        to="catalog.lesson",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lectures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_read_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("cours__isnull", True), ("lesson__isnull", False)
                            ),
                            models.Q(
                                ("cours__isnull", False), ("lesson__isnull", True)
                            ),
                            _connector="OR",
                        ),
                        name="lectureprogress_exactly_one_target",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("lesson__isnull", False)),
                        fields=("user", "lesson"),
                        name="unique_lecture_lesson",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("cours__isnull", False)),
                        fields=("user", "cours"),
                        name="unique_lecture_cours",
                    ),
                ],
            },
        ),
    ]
