# Generated by Django 6.0.7 on 2026-08-08 12:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_referral_code_user_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pseudo',
            field=models.CharField(blank=True, help_text="Nom d'affichage public facultatif, distinct du nom réel - null (pas chaîne vide) tant qu'il n'est pas renseigné, pour rester unique.", max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Le pseudo doit contenir entre 3 et 20 caractères : lettres, chiffres ou underscore.', regex='^[a-zA-Z0-9_]{3,20}$')]),
        ),
    ]
