# Generated by Django 6.0.7 on 2026-08-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_pseudo"),
    ]

    operations = [
        migrations.AddField(
            model_name="otpcode",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="Adresse du demandeur, uniquement pour plafonner les envois par source (voir users.otp_service). Donnée personnelle : jamais exploitée ailleurs, et purgée avec la ligne par purge_otp_codes.",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="otpcode",
            index=models.Index(
                fields=["ip_address", "created_at"],
                name="users_otpco_ip_addr_cfc201_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="otpcode",
            index=models.Index(
                fields=["created_at"], name="users_otpco_created_e8289c_idx"
            ),
        ),
    ]
