# Generated by Django 6.0.7 on 2026-08-19 16:27

from django.db import migrations, models


def _copier_phone_number_vers_destination(apps, schema_editor):
    """
    OTPCode.destination remplace phone_number (fusion des canaux SMS/e-mail dans une
    même table, voir canal) - copié avant suppression du champ plutôt que perdu
    silencieusement, même si ces lignes sont de toute façon éphémères (codes valables
    quelques minutes, purgées sous 7 jours par purge_otp_codes).
    """
    OTPCode = apps.get_model("users", "OTPCode")
    OTPCode.objects.exclude(phone_number="").update(destination=models.F("phone_number"))


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_compte_unique_e164_authidentity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="otpcode",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "code à usage unique",
                "verbose_name_plural": "codes à usage unique",
            },
        ),
        migrations.RemoveIndex(
            model_name="otpcode",
            name="users_otpco_phone_n_d630b2_idx",
        ),
        migrations.RemoveIndex(
            model_name="otpcode",
            name="users_otpco_ip_addr_cfc201_idx",
        ),
        migrations.RemoveIndex(
            model_name="otpcode",
            name="users_otpco_created_e8289c_idx",
        ),
        migrations.AddField(
            model_name="otpcode",
            name="canal",
            field=models.CharField(
                choices=[("sms", "SMS"), ("email", "E-mail")],
                default="sms",
                help_text="Canal d'envoi. Seul `sms` est facturé, d'où les plafonds distincts.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="otpcode",
            name="destination",
            field=models.CharField(
                default="",
                help_text="Numéro au format E.164 pour le canal SMS, adresse e-mail en minuscules pour le canal e-mail. Longueur dimensionnée sur l'adresse e-mail, la plus longue des deux (254 caractères, RFC 5321).",
                max_length=254,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(_copier_phone_number_vers_destination, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="authidentity",
            name="provider",
            field=models.CharField(
                choices=[
                    ("phone", "Téléphone (OTP)"),
                    ("google", "Google"),
                    ("apple", "Apple"),
                    ("email", "E-mail (code)"),
                    ("passkey", "Clé d'accès"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="otpcode",
            index=models.Index(
                fields=["canal", "destination", "is_used"],
                name="users_otpco_canal_7836ec_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="otpcode",
            index=models.Index(
                fields=["canal", "ip_address", "created_at"],
                name="users_otpco_canal_8c9d48_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="otpcode",
            index=models.Index(
                fields=["canal", "created_at"], name="users_otpco_canal_5af470_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="otpcode",
            name="phone_number",
        ),
    ]
