# Generated by Django 6.0.7 on 2026-09-22 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0054_exercise_groupes_verifies_alter_exercise_groupes'),
        ('users', '0007_alter_otpcode_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cursus_prepare',
            field=models.ForeignKey(blank=True, help_text="Cursus que l'utilisateur prépare, déclaré par lui - base du compte à rebours jusqu'à l'examen et, plus tard, de la séance du jour.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eleves', to='catalog.cursus'),
        ),
    ]
