# Generated by Django 6.0.7 on 2026-09-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_backfill_cursus_prepare_depuis_abonnement'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rappels_actifs',
            field=models.BooleanField(default=False, help_text="Accepte un rappel quotidien de sa séance du jour par e-mail (voir relances.services). Jamais activé d'office : seul l'élève le décide, et il ne peut l'être que sur une adresse e-mail confirmée - voir UserProfileUpdateSerializer.validate_rappels_actifs."),
        ),
        migrations.AddField(
            model_name='user',
            name='rappels_invite_refusee_at',
            field=models.DateTimeField(blank=True, help_text="Moment où l'élève a écarté l'invitation à activer les rappels : on ne la lui représente plus. Distinct de rappels_actifs=False, qui est l'état par défaut de quelqu'un à qui on n'a encore rien demandé.", null=True),
        ),
    ]
