# Generated by Django 6.0.7 on 2026-09-30 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0058_seed_exam_sessions_2026_date_fin'),
        ('users', '0010_rappels_quotidiens'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(blank=True, help_text='Affiché partout où le coach quotidien s\'adresse à l\'élève ("Bonjour {prenom}") - distinct du nom du titulaire du compte.', max_length=60)),
                ('rappels_actifs', models.BooleanField(default=False, help_text="Rappel quotidien de LA séance de ce profil par e-mail (voir relances.services) - l'adresse d'envoi reste celle du compte, mais chaque profil active ou non son propre rappel.")),
                ('rappels_invite_refusee_at', models.DateTimeField(blank=True, null=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text="Position stable dans le sélecteur de profils, à l'ajout.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profils', to=settings.AUTH_USER_MODEL)),
                ('cursus_prepare', models.ForeignKey(blank=True, help_text='Cursus que CE profil prépare, déclaré par lui - voir la docstring de la classe : une seule valeur, jamais un M2M.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profils_eleves', to='catalog.cursus')),
            ],
            options={
                'verbose_name': 'profil',
                'verbose_name_plural': 'profils',
                'ordering': ['compte_id', 'ordre', 'created_at'],
            },
        ),
    ]
