# Generated by Django 6.0.7 on 2026-10-02 23:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_backfill_profil_depuis_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='connexion_phone',
            field=models.CharField(blank=True, help_text="Numéro E.164 (vérifié par code) avec lequel l'enfant se connecte lui-même : il ouvre alors une session limitée à ce profil, sans changement d'enfant ni action du compte (paiement, gestion des profils).", max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Le numéro doit être au format international, ex : +237677123456.', regex='^\\+[1-9]\\d{7,14}$')]),
        ),
        migrations.AddField(
            model_name='profil',
            name='pin_bloque_jusqua',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='pin_echecs',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profil',
            name='pin_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='pin_parent_bloque_jusqua',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pin_parent_echecs',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='pin_parent_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
