# Generated by Django 6.0.7 on 2026-10-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_pin_parent_pin_profil_connexion_enfant'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='objectif_xp_quotidien',
            field=models.PositiveSmallIntegerField(default=20, help_text="Rythme que ce profil se fixe, en points d'XP par jour (voir quiz.xp : 10, 20 ou 30). Un jour où il est atteint compte pour la série, comme une séance du jour terminée."),
        ),
    ]
