# Generated by Django 6.0.7 on 2026-10-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_objectif_xp_quotidien'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bilan_parent_actif',
            field=models.BooleanField(default=False, help_text="Reçoit chaque dimanche soir, par e-mail, le bilan de la semaine de chaque profil du compte (voir relances.bilan_parent). Un réglage du TITULAIRE du compte, donc réservé au mode parent, jamais activé d'office, et seulement sur une adresse confirmée - voir UserProfileUpdateSerializer.validate_bilan_parent_actif."),
        ),
    ]
